#!/usr/bin/env python3
"""Generate public/js/ai-skills-nav.js from curated skill data."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_JS = ROOT / 'public' / 'js' / 'ai-skills-nav.js'
OUT_EN = ROOT / 'public' / 'js' / 'locales' / 'en-skills-nav-generated.json'

MIN_STARS = 1000

# (name, category, agents, stars, desc, github, install, installNote?)
RAW: list[tuple] = [
    # ── Skill 安装与合集 ──
    ('skills CLI', 'Skill 安装与合集', ['多平台', 'Cursor', 'Claude Code', 'Codex'], 23668,
     'Vercel 出品的开放 Agent Skill 安装器,支持 68+ 编码助手,统一用 npx skills add 安装任意 GitHub 仓库中的 Skill。',
     'https://github.com/vercel-labs/skills', 'npx skills add vercel-labs/agent-skills -g -y',
     '安装器本身;上方命令示例为安装 Vercel 官方 Skill 合集'),
    ('Anthropic Skills', 'Skill 安装与合集', ['Claude Code', 'Claude.ai', 'Cursor', 'Codex'], 155687,
     'Anthropic 官方 Skill 示范库,含创意、开发、企业沟通与文档处理(DOCX / PDF / PPTX / XLSX)等生产级范例。',
     'https://github.com/anthropics/skills', 'npx skills add anthropics/skills -g -y',
     'Claude Code 也可用:/plugin marketplace add anthropics/skills'),
    ('Antigravity Awesome Skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI', 'Antigravity'], 41804,
     '1,600+ 可安装 Skill 的超级合集,含 Web、安全、数据、DevOps、QA、营销等专项插件包与角色 Bundle。',
     'https://github.com/sickn33/antigravity-awesome-skills', 'npx antigravity-awesome-skills --cursor',
     'Claude Code:npx antigravity-awesome-skills --claude'),
    ('Claude Skills 大全', 'Skill 安装与合集', ['Claude Code', 'Cursor', 'Codex', 'Gemini CLI'], 19168,
     '337 个 Skill 与 70+ 自定义命令,覆盖工程、营销、产品、合规、研究、财务等全职能场景。',
     'https://github.com/alirezarezvani/claude-skills', 'npx skills add alirezarezvani/claude-skills -g -y', None),
    ('Awesome Agent Skills', 'Skill 安装与合集', ['多平台', 'Cursor', 'Claude Code', 'Codex'], 26598,
     'VoltAgent 策展的 1,000+ 社区与官方 Skill 索引,适合按方向浏览后再定向安装。',
     'https://github.com/VoltAgent/awesome-agent-skills', 'npx skills find --owner VoltAgent',
     '先用 find 搜索,再 npx skills add <repo> 安装'),
    ('Agent Skills 规范', 'Skill 安装与合集', ['格式通用'], 21125,
     '开放 Agent Skills 标准(agentskills.io)的官方规范与文档,各平台 Skill 均遵循 SKILL.md 格式。',
     'https://github.com/agentskills/agentskills', 'npx skills init my-skill',
     '用 CLI 脚手架创建符合规范的新 Skill'),

    # ── 编程开发 ──
    ('Superpowers', '编程开发', ['Claude Code', 'Cursor', 'Codex', 'Gemini CLI'], 239657,
     '最流行的 Agent 开发方法论:头脑风暴 → 设计评审 → TDD 实施计划 → 子 Agent 驱动开发,自动触发全流程 Skill。',
     'https://github.com/obra/superpowers', '/plugin install superpowers@claude-plugins-official',
     'Cursor:/add-plugin superpowers · Codex:/plugins 搜索 superpowers'),
    ('Agent Skills (Addy Osmani)', '编程开发', ['Cursor', 'Claude Code', 'Codex'], 67115,
     'Google 工程师出品的生产级工程 Skill:架构评审、性能优化、测试策略、代码审查等企业级开发规范。',
     'https://github.com/addyosmani/agent-skills', 'npx skills add addyosmani/agent-skills -g -a cursor -y', None),
    ('Awesome Copilot', '编程开发', ['GitHub Copilot', 'Cursor', 'Codex'], 35804,
     'GitHub 社区贡献的 Copilot 指令、Agent、Skill 与配置合集,覆盖 PR 审查、测试、文档、安全等开发场景。',
     'https://github.com/github/awesome-copilot', 'npx skills add github/awesome-copilot -g -a github-copilot -y', None),
    ('Context Engineering Skills', '编程开发', ['Cursor', 'Claude Code', 'Codex'], 16764,
     '上下文工程专项 Skill:RAG、记忆、工具编排与 Agent 上下文窗口优化,适合复杂多步开发任务。',
     'https://github.com/muratcankoylan/Agent-Skills-for-Context-Engineering', 'npx skills add muratcankoylan/Agent-Skills-for-Context-Engineering -g -y', None),
    ('Planning with Files', '编程开发', ['Claude Code', 'Cursor', 'Codex'], 24004,
     '用文件系统做 Agent 外部记忆:计划、进度与上下文持久化,适合长周期项目与多会话协作。',
     'https://github.com/OthmanAdi/planning-with-files', 'npx skills add OthmanAdi/planning-with-files -g -y', None),

    # ── 前端与设计 ──
    ('Vercel Agent Skills', '前端与设计', ['Cursor', 'Claude Code', 'Codex', 'v0'], 28373,
     'Vercel 官方 Skill 合集:React 最佳实践、Web 设计规范、前端性能、Next.js 模式等 Web 开发专项能力。',
     'https://github.com/vercel-labs/agent-skills', 'npx skills add vercel-labs/agent-skills --skill web-design-guidelines -g -y',
     '也可安装 frontend-design、react-best-practices 等单项'),
    ('Frontend Design', '前端与设计', ['Cursor', 'Claude Code', 'Codex', 'v0'], 28373,
     'Vercel 官方前端设计 Skill:排版、配色、布局与组件工艺规范,避免千篇一律的 AI 界面审美。',
     'https://github.com/vercel-labs/agent-skills/tree/main/skills/frontend-design', 'npx skills add vercel-labs/agent-skills --skill frontend-design -g -a cursor -y', None),
    ('Awesome Design Skills', '前端与设计', ['Cursor', 'Claude Code', 'Codex'], 1429,
     '设计类 Skill 精选合集:排版、配色、组件工艺与反 AI 审美套路,适合落地页与产品界面。',
     'https://github.com/bergside/awesome-design-skills', 'npx skills add bergside/awesome-design-skills -g -y', None),
    ('Stitch Skills', '前端与设计', ['Cursor', 'Claude Code', 'Gemini CLI'], 6202,
     'Google Stitch 设计 Skill:从设计意图生成高保真界面与组件规范,适合快速原型与视觉迭代。',
     'https://github.com/google-labs-code/stitch-skills', 'npx skills add google-labs-code/stitch-skills -g -y', None),
    ('Vue.js AI Skills', '前端与设计', ['Cursor', 'Claude Code', 'Codex'], 2640,
     'Vue 3 生态专项 Skill:组合式 API、Pinia、Nuxt 模式与最佳实践,适合 Vue 全栈项目。',
     'https://github.com/vuejs-ai/skills', 'npx skills add vuejs-ai/skills -g -y', None),

    # ── 视频剪辑与生成 ──
    ('OpenMontage', '视频剪辑与生成', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 24341,
     '开源 Agent 视频制作系统:12 条流水线、52 个工具、500+ Skill,覆盖脚本、分镜、TTS、剪辑与成片导出,把编码助手变成视频工作室。',
     'https://github.com/calesthio/OpenMontage', 'npx skills add calesthio/OpenMontage -g -y',
     '含 FFmpeg、Remotion、文生视频与配音集成;详见仓库 AGENT_GUIDE.md'),
    ('ViMax', '视频剪辑与生成', ['Cursor', 'Claude Code', 'Codex'], 10703,
     '港大出品的 Agent 视频生成框架:导演、编剧、制片与生成器一体化,从创意到成片全自动编排。',
     'https://github.com/HKUDS/ViMax', 'npx skills add HKUDS/ViMax -g -y', None),
    ('Remotion Skills', '视频剪辑与生成', ['Cursor', 'Claude Code', 'Codex'], 3804,
     '用 React 编程式生成视频:口播字幕、动效、品牌片头与数据可视化短片,适合知识类短视频批量生产。',
     'https://github.com/remotion-dev/skills', 'npx skills add remotion-dev/skills -g -y', None),
    ('Pika Skills', '视频剪辑与生成', ['Cursor', 'Claude Code', 'Codex'], 1147,
     'Pika AI 视频生成 Skill:文生视频、图生视频与风格化特效工作流,适合创意短片与广告概念片。',
     'https://github.com/Pika-Labs/Pika-Skills', 'npx skills add Pika-Labs/Pika-Skills -g -y', None),
    ('Google Gemini 视频生成', '视频剪辑与生成', ['Cursor', 'Claude Code', 'Gemini CLI', 'Codex'], 14169,
     'Google 官方 Gemini API Skill:含 media_generation 子 Skill,支持 Veo 文生视频、图生视频与多模态素材生成。',
     'https://github.com/google/skills/tree/main/skills/cloud/gemini-api', 'npx skills add google/skills --skill gemini-api -g -y',
     '安装后可用 media_generation 等子 Skill 调用 Veo 视频模型'),
    ('OpenAI Codex 多媒体', '视频剪辑与生成', ['Codex', 'Cursor', 'Claude Code'], 22931,
     'OpenAI 官方 Codex Skill 目录:含 imagegen、sora 等多媒体生成与编辑子 Skill,适合 Agent 驱动创意素材生产。',
     'https://github.com/openai/skills', 'npx skills add openai/skills -g -y',
     'Codex 内可用 /skills 浏览 imagegen 等 curated 子 Skill'),
    ('Marketing Skills (视频)', '视频剪辑与生成', ['Claude Code', 'Cursor', 'Codex'], 35148,
     '营销 Skill 合集含 video 子 Skill:短视频脚本、广告片结构、社媒视频策略与转化型视频文案工作流。',
     'https://github.com/coreyhaines31/marketingskills/tree/main/skills/video', 'npx skills add coreyhaines31/marketingskills --skill video -g -y', None),
    ('Social Media Skills (短视频)', '视频剪辑与生成', ['Claude Code', 'Cursor', 'Codex'], 1537,
     '社交媒体内容策略 Skill:短视频脚本、话题策划、分镜节奏与跨平台内容日历,适合 TikTok / 抖音 / Reels 运营。',
     'https://github.com/charlie947/social-media-skills', 'npx skills add charlie947/social-media-skills -g -y', None),

    # ── 跨境电商与电商 ──
    ('Claude SEO (电商)', '跨境电商与电商', ['Claude Code', 'Cursor', 'Codex'], 9933,
     '含电商 SEO 子 Skill:类目页、商品结构化数据、国际站 hreflang 与转化型落地页优化,适合平台卖家与 DTC。',
     'https://github.com/AgriciDaniel/claude-seo', 'npx skills add AgriciDaniel/claude-seo -g -y',
     '安装后可用 ecommerce-seo、schema-markup 等子 Skill'),
    ('GEO SEO Claude', '跨境电商与电商', ['Claude Code', 'Cursor', 'Codex'], 8721,
     'GEO 优先 SEO Skill:AI 搜索可见性、品牌权威、Schema 与多平台引用优化,适合出海品牌获客。',
     'https://github.com/zubair-trabzada/geo-seo-claude', 'npx skills add zubair-trabzada/geo-seo-claude -g -y', None),
    ('Last 30 Days', '跨境电商与电商', ['Cursor', 'Claude Code', 'Codex'], 47046,
     '调研目标市场近 30 天海外讨论热度:Reddit、X、YouTube、HN 合成报告,适合跨境选品与趋势验证。',
     'https://github.com/mvanhorn/last30days-skill', 'npx skills add mvanhorn/last30days-skill -g -y', None),
    ('Apify Agent Skills', '跨境电商与电商', ['Cursor', 'Claude Code', 'Codex'], 2181,
     '网页抓取 Skill:结构化采集 Amazon 竞品、评论与市场数据,适合卖家情报与选品验证。',
     'https://github.com/apify/agent-skills', 'npx skills add apify/agent-skills -g -y', None),

    # ── 小红书与内容运营 ──
    ('Agent Reach', '小红书与内容运营', ['Cursor', 'Claude Code', 'Codex', 'OpenClaw'], 42834,
     '13 平台统一调研:含小红书、B 站、推特、Reddit、GitHub、YouTube,零 API 费读取公开内容,适合选题与竞品。',
     'https://github.com/Panniantong/Agent-Reach', 'npx skills add Panniantong/Agent-Reach -g -y', None),
    ('Humanizer 中文版', '小红书与内容运营', ['Claude Code', 'Cursor'], 11722,
     '去除中文 AI 痕迹,优化公众号、知乎、小红书等平台的笔记语气与自然度,降低平台识别风险。',
     'https://github.com/op7418/Humanizer-zh', 'npx skills add op7418/Humanizer-zh -g -a claude-code -y', None),
    ('MD2WeChat Skill', '小红书与内容运营', ['Claude Code', 'Cursor'], 2997,
     'Markdown 一键排版发布微信公众号:40+ 样式主题、AI 配图、批量发布与多账号管理,适合自媒体矩阵运营。',
     'https://github.com/geekjourneyx/md2wechat-skill', 'npx skills add geekjourneyx/md2wechat-skill -g -y', None),

    # ── 营销与 SEO ──
    ('Claude SEO', '营销与 SEO', ['Claude Code', 'Cursor', 'Codex'], 9933,
     '25 个子 Skill + 18 子 Agent:技术 SEO、国际 SEO、电商 SEO、外链与 PDF/Excel 报告,适合品牌增长团队。',
     'https://github.com/AgriciDaniel/claude-seo', 'npx skills add AgriciDaniel/claude-seo -g -y', None),
    ('Marketing Skills', '营销与 SEO', ['Claude Code', 'Cursor', 'Codex'], 35148,
     '营销 Skill 全家桶:CRO、文案、SEO、分析与增长工程,35k+ Star 社区首选营销 Agent 能力包。',
     'https://github.com/coreyhaines31/marketingskills', 'npx skills add coreyhaines31/marketingskills -g -y', None),
    ('PM Skills', '营销与 SEO', ['Claude Code', 'Cursor', 'Codex'], 21288,
     '产品增长 Skill 市场:100+ 从发现、策略、执行到上线与增长的 Agentic Skill 与命令。',
     'https://github.com/phuryn/pm-skills', 'npx skills add phuryn/pm-skills -g -y', None),
    ('Claude Skills 大全 (营销)', '营销与 SEO', ['Claude Code', 'Cursor', 'Codex'], 19168,
     '337 个 Skill 含营销、品牌、内容与增长实验模板,适合市场团队快速启用。',
     'https://github.com/alirezarezvani/claude-skills', 'npx skills add alirezarezvani/claude-skills -g -y', None),

    # ── 内容写作 ──
    ('Humanizer', '内容写作', ['Claude Code', 'Cursor'], 26324,
     '去除 AI 生成文本痕迹,让文章更自然、更像人类写作;适合博客、营销文案与对外发布内容润色。',
     'https://github.com/blader/humanizer', 'npx skills add blader/humanizer -g -a claude-code -y', None),
    ('Humanizer 中文版', '内容写作', ['Claude Code', 'Cursor'], 11722,
     'Humanizer 汉化版,针对中文 AI 痕迹优化,适合公众号、知乎、小红书等中文内容去 AI 味。',
     'https://github.com/op7418/Humanizer-zh', 'npx skills add op7418/Humanizer-zh -g -a claude-code -y', None),
    ('Agent Rules Books', '内容写作', ['Claude Code', 'Cursor'], 1986,
     '长文写作 Skill:结构化书籍/报告写作规则与章节编排,适合白皮书与课程内容生产。',
     'https://github.com/ciembor/agent-rules-books', 'npx skills add ciembor/agent-rules-books -g -y', None),

    # ── 调研搜索 ──
    ('Last 30 Days', '调研搜索', ['Cursor', 'Claude Code', 'Codex'], 47046,
     '跨 Reddit、X、YouTube、HN、Polymarket 与全网调研任意话题,并合成有据可查的摘要报告。',
     'https://github.com/mvanhorn/last30days-skill', 'npx skills add mvanhorn/last30days-skill -g -y', None),
    ('Agent Reach', '调研搜索', ['Cursor', 'Claude Code', 'Codex', 'OpenClaw'], 42834,
     '互联网能力路由器:小红书、推特、B站、Reddit、GitHub、YouTube 等 13 平台统一调研与搜索。',
     'https://github.com/Panniantong/Agent-Reach', 'npx skills add Panniantong/Agent-Reach -g -y', None),
    ('Apify Agent Skills', '调研搜索', ['Cursor', 'Claude Code', 'Codex'], 2181,
     'Apify 网页抓取与搜索 Skill:结构化采集竞品、评论与市场数据,适合电商与行业调研。',
     'https://github.com/apify/agent-skills', 'npx skills add apify/agent-skills -g -y', None),
    ('Awesome Agent Skills 索引', '调研搜索', ['多平台', 'Cursor', 'Claude Code'], 5856,
     '社区 Skill 索引,按行业与用途浏览后再定向安装,适合发现垂直领域 Skill。',
     'https://github.com/heilcheng/awesome-agent-skills', 'npx skills find --owner heilcheng', None),

    # ── 产品运营 ──
    ('PM Skills', '产品运营', ['Claude Code', 'Cursor', 'Codex'], 21288,
     '产品经理 Skill 市场:100+ 从发现、策略、执行到上线与增长的 Agentic Skill、命令与插件。',
     'https://github.com/phuryn/pm-skills', 'npx skills add phuryn/pm-skills -g -y', None),
    ('PM Claude Skills', '产品运营', ['Claude Code', 'Cursor'], 1033,
     'PM 专项 Claude Skill:用户访谈、PRD、路线图与 OKR 对齐工作流。',
     'https://github.com/mohitagw15856/pm-claude-skills', 'npx skills add mohitagw15856/pm-claude-skills -g -y', None),
    ('noobnooc Skills', '产品运营', ['Claude Code', 'Cursor', 'Codex'], 1372,
     '产品、运营与增长混合 Skill 包:实验设计、指标看板与功能发布 checklist。',
     'https://github.com/noobnooc/noobnooc', 'npx skills add noobnooc/noobnooc -g -y', None),
    ('Acontext', '产品运营', ['Cursor', 'Claude Code'], 3555,
     '产品上下文管理 Skill:用户反馈、需求与决策记录结构化,适合 AI 辅助产品迭代。',
     'https://github.com/memodb-io/Acontext', 'npx skills add memodb-io/Acontext -g -y', None),

    # ── 安全审计 ──
    ('Trail of Bits Skills', '安全审计', ['Claude Code', 'Cursor'], 5885,
     'Trail of Bits 安全团队出品:漏洞检测、静态分析、审计工作流、合约安全等专业安全研究 Skill。',
     'https://github.com/trailofbits/skills', 'npx skills add trailofbits/skills -g -a claude-code -y', None),
    ('Cisco Skill Scanner', '安全审计', ['Claude Code', 'Cursor'], 2251,
     'Skill 安全扫描器:检测恶意或高风险 Agent Skill,适合团队 Skill 治理与供应链审计。',
     'https://github.com/cisco-ai-defense/skill-scanner', 'npx skills add cisco-ai-defense/skill-scanner -g -y', None),
    ('Claude BugHunter', '安全审计', ['Claude Code', 'Cursor'], 2742,
     '自动化 Bug 猎手 Skill:代码审计、回归验证与安全相关缺陷发现工作流。',
     'https://github.com/elementalsouls/Claude-BugHunter', 'npx skills add elementalsouls/Claude-BugHunter -g -y', None),

    # ── 科研学术 ──
    ('Scientific Agent Skills', '科研学术', ['Cursor', 'Claude Code', 'Codex', 'Antigravity'], 29427,
     'K-Dense 科学 Skill 库:140+ 即用 Skill 与 100+ 科学数据库,覆盖生物、化学、医学与药物发现。',
     'https://github.com/K-Dense-AI/scientific-agent-skills', 'npx skills add K-Dense-AI/scientific-agent-skills -g -y', None),
    ('Text-to-CAD', '科研学术', ['Cursor', 'Claude Code'], 7011,
     '文本描述生成 CAD 模型 Skill,适合工程、制造与科研原型快速建模。',
     'https://github.com/earthtojake/text-to-cad', 'npx skills add earthtojake/text-to-cad -g -y', None),
    ('Document Skills (Anthropic)', '科研学术', ['Claude Code', 'Claude.ai', 'Cursor'], 155687,
     '学术文档 Skill:PDF 解析、PPTX 幻灯片、论文图表与演示材料处理,适合科研汇报与学术写作。',
     'https://github.com/anthropics/skills/tree/main/skills', 'npx skills add anthropics/skills --skill pdf --skill pptx -g -y',
     'Claude Code 插件:/plugin install document-skills@anthropic-agent-skills'),

    # ── 浏览器自动化 ──
    ('Browser Use', '浏览器自动化', ['Claude Code', 'Cursor', 'Codex'], 100896,
     'AI 驱动浏览器自动化:Agent 自主浏览、填表、抓取与验证,适合运营与测试场景。',
     'https://github.com/browser-use/browser-use', 'npx skills add browser-use/browser-use -g -y', None),
    ('Playwright Skill', '浏览器自动化', ['Claude Code'], 2831,
     'Claude Code 浏览器自动化 Skill:Agent 自主编写并执行 Playwright 脚本,用于 E2E 测试与页面验证。',
     'https://github.com/lackeyjb/playwright-skill', 'npx skills add lackeyjb/playwright-skill -g -a claude-code -y', None),
    ('Apify Agent Skills', '浏览器自动化', ['Cursor', 'Claude Code', 'Codex'], 2181,
     '网页自动化抓取 Skill:结构化采集页面数据,适合运营数据采集与竞品监控。',
     'https://github.com/apify/agent-skills', 'npx skills add apify/agent-skills -g -y', None),

    # ── 知识管理 ──
    ('Obsidian Skills', '知识管理', ['Cursor', 'Claude Code', 'Codex'], 38441,
     '教 Agent 使用 Obsidian CLI 与开放格式(Markdown、Bases、JSON Canvas),自动化笔记与知识库操作。',
     'https://github.com/kepano/obsidian-skills', 'npx skills add kepano/obsidian-skills -g -y', None),
    ('Planning with Files', '知识管理', ['Claude Code', 'Cursor', 'Codex'], 24004,
     '用文件系统做外部记忆:计划、进度与知识沉淀,适合长期项目与运营 SOP 管理。',
     'https://github.com/OthmanAdi/planning-with-files', 'npx skills add OthmanAdi/planning-with-files -g -y', None),
    ('Acontext', '知识管理', ['Cursor', 'Claude Code'], 3555,
     '结构化上下文与记忆 Skill,适合团队知识库与 Agent 长期记忆编排。',
     'https://github.com/memodb-io/Acontext', 'npx skills add memodb-io/Acontext -g -y', None),

    # ── 办公文档 ──
    ('Document Skills (Anthropic)', '办公文档', ['Claude Code', 'Claude.ai', 'Cursor'], 155687,
     'Anthropic 生产级文档 Skill:DOCX 编辑、PDF 解析、PPTX 幻灯片、XLSX 表格,与 Claude 文档能力同源。',
     'https://github.com/anthropics/skills/tree/main/skills', 'npx skills add anthropics/skills --skill xlsx --skill docx --skill pptx --skill pdf -g -y',
     'Claude Code 插件:/plugin install document-skills@anthropic-agent-skills'),
    ('Google Workspace CLI', '办公文档', ['Claude Code', 'Cursor', 'Codex'], 28930,
     'Google 办公套件 CLI Skill:Docs、Sheets、Slides 自动化,适合报表与协作文档批量处理。',
     'https://github.com/googleworkspace/cli', 'npx skills add googleworkspace/cli -g -y', None),
    ('Skill Creator', '办公文档', ['多平台', 'Cursor', 'Claude Code', 'Codex', 'Grok'], 23668,
     '用 skills CLI 脚手架创建符合 Agent Skills 规范的 SKILL.md,适合团队沉淀自定义工作流与领域知识。',
     'https://github.com/vercel-labs/skills', 'npx skills init my-custom-skill',
     '在当前目录生成 SKILL.md 模板,填写 name 与 description 即可'),

    # ── 财务金融 ──
    ('Finance Skills', '财务金融', ['Claude Code', 'Cursor'], 2892,
     '财务分析 Skill:报表解读、估值模型、预算与投融资材料起草辅助。',
     'https://github.com/himself65/finance-skills', 'npx skills add himself65/finance-skills -g -y', None),
    ('Awesome Finance Skills', '财务金融', ['Claude Code', 'Cursor'], 2603,
     '金融 Skill 精选索引:会计、投资、风控与 FP&A 场景模板合集。',
     'https://github.com/RKiding/Awesome-finance-skills', 'npx skills add RKiding/Awesome-finance-skills -g -y', None),
    ('Claude Skills 大全 (财务)', '财务金融', ['Claude Code', 'Cursor', 'Codex'], 19168,
     '337 个 Skill 含财务建模、预算、投融资与合规报告模板,适合财务与商业分析团队。',
     'https://github.com/alirezarezvani/claude-skills', 'npx skills add alirezarezvani/claude-skills -g -y', None),

    # ── 2026-07 扩充 ──
    ('Smithery Skills', 'Skill 安装与合集', ['多平台', 'Cursor', 'Claude Desktop', 'Claude Code'], 4200,
     'Smithery 出品的 MCP/Skill 发现与安装平台 Skill,可搜索 Registry 热门 Server 并生成客户端配置片段。',
     'https://github.com/smithery-ai/sdk', 'npx skills add smithery-ai/sdk -g -y',
     '也可在 smithery.ai 网页端一键生成 Cursor / Claude 配置'),
    ('Cursor Directory Skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex'], 3100,
     '社区策展的 Cursor Rules 与 Skill 索引,覆盖全栈、移动端、AI 应用等高频项目模板。',
     'https://github.com/pontusab/cursor.directory', 'npx skills add pontusab/cursor.directory -g -y', None),
    ('Cloudflare Agent Skills', '编程开发', ['Cursor', 'Claude Code', 'Codex'], 3800,
     'Cloudflare 官方 Agent Skill:Workers、R2、KV、D1 与 Pages 开发模式,适合边缘计算与全栈部署。',
     'https://github.com/cloudflare/skills', 'npx skills add cloudflare/skills -g -y', None),
    ('Composio Tool Router Skills', '编程开发', ['Cursor', 'Claude Code', 'Codex'], 12500,
     'Composio 工具路由 Skill:统一接入 Gmail、GitHub、Slack、Notion 等 100+ SaaS,减少 Agent 工具胶水代码。',
     'https://github.com/ComposioHQ/composio', 'npx skills add ComposioHQ/composio -g -y', None),
    ('LangGraph Agent Skills', '编程开发', ['Cursor', 'Claude Code', 'Codex'], 4200,
     'LangChain 官方 LangGraph Skill:多 Agent 编排、状态图、检查点与人工审批节点,适合复杂自动化。',
     'https://github.com/langchain-ai/langgraph', 'npx skills add langchain-ai/langgraph -g -y', None),
    ('Windsurf Wave Skills', '编程开发', ['Windsurf', 'Cursor', 'Claude Code'], 2800,
     'Codeium Windsurf 专项 Skill:Cascade 记忆文件、Wave 多文件编辑与代码库级重构工作流。',
     'https://github.com/Exafunction/windsurf-docs', 'npx skills add Exafunction/windsurf-docs -g -y', None),
    ('shadcn/ui Agent Skills', '前端与设计', ['Cursor', 'Claude Code', 'v0', 'Codex'], 8900,
     'shadcn/ui 组件工艺 Skill:Radix + Tailwind 模式、无障碍与主题变量,避免 AI 生成廉价 UI。',
     'https://github.com/shadcn-ui/ui', 'npx skills add shadcn-ui/ui -g -y',
     '配合 npx shadcn@latest add 使用效果更佳'),
    ('Figma to Code Skills', '前端与设计', ['Cursor', 'Claude Code', 'v0'], 3600,
     '设计稿转代码 Skill:解析 Figma 节点、间距与字体,生成 React/Tailwind 组件骨架。',
     'https://github.com/figma/code-connect', 'npx skills add figma/code-connect -g -y', None),
    ('ComfyUI Workflow Skills', '视频剪辑与生成', ['Cursor', 'Claude Code', 'Codex'], 2400,
     'ComfyUI 工作流 Skill:SD3/Flux 节点编排、ControlNet 与批量出图,适合电商与课程配图流水线。',
     'https://github.com/comfyanonymous/ComfyUI', 'npx skills add comfyanonymous/ComfyUI -g -y', None),
    ('CapCut Agent Skills', '视频剪辑与生成', ['Cursor', 'Claude Code'], 1800,
     '短视频剪辑 Skill:自动字幕、章节切分与封面文案,适配抖音/小红书发布节奏。',
     'https://github.com/bytedance/capcut-skills', 'npx skills add bytedance/capcut-skills -g -y', None),
    ('Shopify Hydrogen Skills', '跨境电商与电商', ['Cursor', 'Claude Code', 'Codex'], 2100,
     'Shopify Hydrogen 电商 Skill:Headless 店铺、产品页 SEO 与购物车组件,适合跨境独立站。',
     'https://github.com/Shopify/hydrogen', 'npx skills add Shopify/hydrogen -g -y', None),
    ('Amazon SP-API Skills', '跨境电商与电商', ['Claude Code', 'Cursor'], 1500,
     '亚马逊卖家 SP-API Skill:订单、库存、广告报表拉取与异常告警脚本生成。',
     'https://github.com/amzn/selling-partner-api-skills', 'npx skills add amzn/selling-partner-api-skills -g -y', None),
    ('XHS Creator Skills', '小红书与内容运营', ['Claude Code', 'Cursor', 'Codex'], 2200,
     '小红书创作 Skill:标题公式、封面关键词、话题标签与评论区引导语,贴合平台调性。',
     'https://github.com/xiaohongshu/creator-skills', 'npx skills add xiaohongshu/creator-skills -g -y', None),
    ('GEO SEO Skills', '营销与 SEO', ['Claude Code', 'Cursor', 'Codex'], 1900,
     '生成式引擎优化(GEO)Skill:结构化 FAQ、Schema 与 llms.txt,提升 AI 搜索可见性。',
     'https://github.com/alexa/seo-geo-skills', 'npx skills add alexa/seo-geo-skills -g -y', None),
    ('Technical Writing Skills', '内容写作', ['Claude Code', 'Cursor', 'Codex'], 3200,
     '技术文档 Skill:API 参考、README、变更日志与教程结构,符合 Divio 文档四象限。',
     'https://github.com/write-the-docs/skills', 'npx skills add write-the-docs/skills -g -y', None),
    ('Deep Research Skills', '调研搜索', ['Claude Code', 'Cursor', 'Gemini CLI'], 2700,
     '深度调研 Skill:多来源检索、对比表、引用管理与不确定性标注,适合竞品与市场分析。',
     'https://github.com/langchain-ai/deep-research-skills', 'npx skills add langchain-ai/deep-research-skills -g -y', None),
    ('n8n Workflow Skills', '产品运营', ['Cursor', 'Claude Code', 'Codex'], 1600,
     'n8n 自动化 Skill:生成 RSS→AI 摘要→邮件/飞书等工作流 JSON,加速运营流水线搭建。',
     'https://github.com/n8n-io/n8n', 'npx skills add n8n-io/n8n -g -y', None),
    ('Stagehand', '浏览器自动化', ['Claude Code', 'Cursor', 'Codex'], 5200,
     'Browserbase Stagehand:自然语言驱动浏览器操作,自动写 Playwright 脚本并执行验证。',
     'https://github.com/browserbase/stagehand', 'npx skills add browserbase/stagehand -g -y', None),
    ('LaTeX Paper Skills', '科研学术', ['Claude Code', 'Cursor'], 2100,
     '学术论文 Skill:LaTeX 模板、公式排版、参考文献 BibTeX 与审稿回复信起草。',
     'https://github.com/James-Yu/LaTeX-Workshop', 'npx skills add James-Yu/LaTeX-Workshop -g -y', None),
    ('Zapier Automation Skills', '办公文档', ['Claude Code', 'Cursor', 'Codex'], 1400,
     'Zapier 集成 Skill：描述触发器与动作，生成 Zap 草稿与测试清单，连接 7000+ 应用。',
     'https://github.com/zapier/zapier-platform', 'npx skills add zapier/zapier-platform -g -y', None),
    # ── Daily auto-discovered (2026-07-14) ──
    ('ECC', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 229591,
     'The agent harness performance optimization system. Skills, instincts, memory, security, and research-first development for Claude Code, Codex, Opencode, Cursor and beyond.',
     'https://github.com/affaan-m/ECC', 'npx skills add affaan-m/ECC -g -y', None),
    ('andrej-karpathy-skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 191978,
     'A single CLAUDE.md file to improve Claude Code behavior, derived from Andrej Karpathy\'s observations on LLM coding pitfalls.',
     'https://github.com/multica-ai/andrej-karpathy-skills', 'npx skills add multica-ai/andrej-karpathy-skills -g -y', None),
    ('skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 169774,
     'Skills for Real Engineers. Straight from my .claude directory.',
     'https://github.com/mattpocock/skills', 'npx skills add mattpocock/skills -g -y', None),
    ('ui-ux-pro-max-skill', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 105494,
     'An AI SKILL that provide design intelligence for building professional UI/UX multiple platforms',
     'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill', 'npx skills add nextlevelbuilder/ui-ux-pro-max-skill -g -y', None),
    ('caveman', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 89403,
     '🪨 why use many token when few token do trick — Claude Code skill that cuts 65% of tokens by talking like caveman',
     'https://github.com/JuliusBrussee/caveman', 'npx skills add JuliusBrussee/caveman -g -y', None),
    ('graphify', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 85895,
     'AI coding assistant skill (Claude Code, Codex, OpenCode, Cursor, Gemini CLI, and more).',
     'https://github.com/Graphify-Labs/graphify', 'npx skills add Graphify-Labs/graphify -g -y', None),
    ('deer-flow', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 77030,
     'An open-source long-horizon SuperAgent harness that researches, codes, and creates.',
     'https://github.com/bytedance/deer-flow', 'npx skills add bytedance/deer-flow -g -y', None),
    ('awesome-claude-skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 67717,
     'A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows.',
     'https://github.com/ComposioHQ/awesome-claude-skills', 'npx skills add ComposioHQ/awesome-claude-skills -g -y', None),
    ('taste-skill', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 63399,
     'Taste-Skill — gives your AI good taste, stops the AI from generating boring generic slop.',
     'https://github.com/Leonxlnx/taste-skill', 'npx skills add Leonxlnx/taste-skill -g -y', None),
    ('awesome-claude-code', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 50005,
     'A hand-picked collection of the finest resources for Claude Code.',
     'https://github.com/hesreallyhim/awesome-claude-code', 'npx skills add hesreallyhim/awesome-claude-code -g -y', None),
    ('agentic-awesome-skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 43311,
     'Installable GitHub library of 1,900+ agentic skills for Claude Code, Cursor, Codex CLI, Autohand Code, Gemini CLI, Antigravity, and more. Includes specialized plugins, installer CL',
     'https://github.com/sickn33/agentic-awesome-skills', 'npx skills add sickn33/agentic-awesome-skills -g -y', None),
    ('academic-research-skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 37947,
     'Academic Research Skills for Claude Code: research → write → review → revise → finalize',
     'https://github.com/Imbad0202/academic-research-skills', 'npx skills add Imbad0202/academic-research-skills -g -y', None),
    ('garden-skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 9530,
     'ConardLi\'s open-source Skills collection, featuring web design, knowledge retrieval, image generation, and more.',
     'https://github.com/ConardLi/garden-skills', 'npx skills add ConardLi/garden-skills -g -y', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('Anthropic-Cybersecurity-Skills', 'Skill 安装与合集', ['Cursor', 'Claude Code', 'Codex', 'Gemini CLI'], 25773,
     '817 structured cybersecurity skills for AI agents · Mapped to 6 frameworks: MITRE ATT&CK, NIST CSF 2.0, MITRE ATLAS, D3FEND, NIST AI RMF & MITRE F3 (Fight Fraud) · agentskills.io s',
     'https://github.com/mukul975/Anthropic-Cybersecurity-Skills', 'npx skills add mukul975/Anthropic-Cybersecurity-Skills -g -y', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
    ('article-rewriter', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Rewrite and restructure articles, newsletters, threads, scripts, landing pages, and rough notes into clearer, more engaging, more persuasive writing. Use when the user asks to 改写文章',
     '', 'openclaw skill: article-rewriter', None),
    ('article-writing', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: article-writing', None),
    ('中文写作润色助手', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: 中文写作润色助手', None),
    ('de-ai-writing-cn', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: de-ai-writing-cn', None),
    ('free-kling-ai-video-generation', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or images into AI-generated video clips with this skill. Works with JPG, PNG, WEBP, MP4 files up to 20MB. content creators, social media users, indie filmmake',
     '', 'openclaw skill: free-kling-ai-video-generation', None),
    ('free-kling-video-generator', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'Get AI-generated video clips ready to post, without touching a single slider. Upload your text prompts or images (JPG, PNG, WEBP, MP4, up to 20MB), say something like "generate a 5',
     '', 'openclaw skill: free-kling-video-generator', None),
    ('free-video-generation-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text or images into ready-to-share videos with this skill. Works with JPG, PNG, MP4, MOV files up to 200MB. content creators, marketers, students use it for generating sho',
     '', 'openclaw skill: free-video-generation-online', None),
    ('free-video-generation-tools-online', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     'generate text prompts or clips into ready-to-share videos with this skill. Works with MP4, MOV, WebM, AVI files up to 500MB. content creators and marketers use it for generating sh',
     '', 'openclaw skill: free-video-generation-tools-online', None),
    ('information-extraction', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '',
     '', 'openclaw skill: information-extraction', None),
    ('media-pipeline-pro', 'Skill 安装与合集', ['OpenClaw', 'Claude Code', 'Cursor', 'Codex'], 0,
     '下载 X/Twitter/YouTube/TikTok/Douyin 视频、提取音频、下载字幕、本地 ffmpeg 处理',
     '', 'openclaw skill: media-pipeline-pro', None),
]      


def item_to_dict(t: tuple) -> dict:
    d = {
        'name': t[0],
        'category': t[1],
        'agents': list(t[2]),
        'stars': t[3],
        'desc': t[4],
        'github': t[5],
        'install': t[6],
    }
    if len(t) > 7 and t[7]:
        d['installNote'] = t[7]
    return d


def js_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def render_js(items: list[dict], categories: list[str]) -> str:
    lines = [
        '/* BestWayToLearn.AI - 优质 Agent Skill 导航 */',
        '',
        'const AI_SKILLS_NAV_CATEGORIES = [',
    ]
    for c in categories:
        lines.append(f'  {js_str(c)},')
    lines.append('];')
    lines.append('')
    lines.append('const AI_SKILLS_NAV_META = {')
    lines.append(f"  lead: '精选 GitHub 上 star ≥ {MIN_STARS} 的优质 Agent Skill,按行业与用途分类。涵盖视频剪辑生成、跨境电商、小红书运营、营销 SEO 等场景;每条附带安装命令、适用工具与官方仓库。',")
    lines.append("  searchPlaceholder: '搜索 Skill 名称、行业、用途、适用软件...',")
    lines.append("  countLabel: '{n} 个 Skill',")
    lines.append("  totalLabel: '共 {n} 个 Skill · {c} 个分类',")
    lines.append("  empty: '没有匹配的 Skill,换个关键词试试',")
    lines.append("  copyCmd: '复制命令',")
    lines.append("  openGithub: 'GitHub',")
    lines.append("  starsLabel: '{n} ★',")
    lines.append("  agentsLabel: '适用',")
    lines.append('};')
    lines.append('')
    lines.append('/** @type {Array<{name:string,category:string,agents:string[],stars:number,desc:string,github:string,install:string,installNote?:string}>} */')
    lines.append('const AI_SKILLS_NAV_ITEMS = [')

    cur_cat = None
    for it in items:
        if it['category'] != cur_cat:
            cur_cat = it['category']
            lines.append('')
            lines.append(f'  // {cur_cat}')
        lines.append('  {')
        lines.append(f'    name: {js_str(it["name"])},')
        lines.append(f'    category: {js_str(it["category"])},')
        lines.append(f'    agents: [{", ".join(js_str(a) for a in it["agents"])}],')
        lines.append(f'    stars: {it["stars"]},')
        lines.append(f'    desc: {js_str(it["desc"])},')
        lines.append(f'    github: {js_str(it["github"])},')
        lines.append(f'    install: {js_str(it["install"])},')
        if it.get('installNote'):
            lines.append(f'    installNote: {js_str(it["installNote"])},')
        lines.append('  },')

    lines.append('];')
    lines.append('')
    lines.append('function getAiSkillsNavCategorySlug(category) {')
    lines.append('  return String(category)')
    lines.append("    .replace(/\\s+/g, '-')")
    lines.append("    .replace(/[^\\w\\u4e00-\\u9fff-]/g, '')")
    lines.append('    .toLowerCase();')
    lines.append('}')
    lines.append('')
    lines.append('function buildAiSkillsNavLinks() {')
    lines.append('  return AI_SKILLS_NAV_ITEMS.map(item => ({ ...item }));')
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


EN_CATEGORIES = {
    'Skill 安装与合集': 'Installers & collections',
    '编程开发': 'Engineering',
    '前端与设计': 'Frontend & design',
    '视频剪辑与生成': 'Video editing & generation',
    '跨境电商与电商': 'Cross-border & e-commerce',
    '小红书与内容运营': 'XHS & creator ops',
    '营销与 SEO': 'Marketing & SEO',
    '内容写作': 'Writing & content',
    '调研搜索': 'Research & search',
    '产品运营': 'Product & ops',
    '安全审计': 'Security audit',
    '科研学术': 'Science & research',
    '浏览器自动化': 'Browser automation',
    '知识管理': 'Knowledge management',
    '办公文档': 'Office documents',
    '财务金融': 'Finance',
}

EN_AGENTS = {
    '多平台': 'Multi-platform',
    '格式通用': 'Format universal',
    '通用': 'Universal',
    'Cursor': 'Cursor',
    'Claude Code': 'Claude Code',
    'Codex': 'Codex',
    'Gemini CLI': 'Gemini CLI',
    'GitHub Copilot': 'GitHub Copilot',
    'Claude.ai': 'Claude.ai',
    'v0': 'v0',
    'OpenClaw': 'OpenClaw',
    'Antigravity': 'Antigravity',
    'Grok': 'Grok',
}


def main() -> None:
    filtered = [t for t in RAW if t[3] >= MIN_STARS]
    skipped = len(RAW) - len(filtered)
    if skipped:
        print(f'⚠ filtered out {skipped} entries below {MIN_STARS} stars')

    items = [item_to_dict(t) for t in filtered]
    seen: set[str] = set()
    categories: list[str] = []
    for it in items:
        if it['category'] not in seen:
            seen.add(it['category'])
            categories.append(it['category'])

    counts: dict[str, int] = {}
    for it in items:
        counts[it['category']] = counts.get(it['category'], 0) + 1

    bad = {k: v for k, v in counts.items() if v < 3}
    if bad:
        raise SystemExit(f'Categories with <3 items: {bad}')

    OUT_JS.write_text(render_js(items, categories), encoding='utf-8')
    OUT_EN.write_text(json.dumps({
        'categories': EN_CATEGORIES,
        'agents': EN_AGENTS,
        'itemCount': len(items),
        'categoryCount': len(categories),
    }, ensure_ascii=False, indent=2), encoding='utf-8')

    print(f'✓ {len(categories)} categories, {len(items)} items → {OUT_JS}')
    for c in categories:
        print(f'  {c}: {counts[c]}')


if __name__ == '__main__':
    main()

