#!/usr/bin/env python3
"""Generate 40 briefing + 40 tutorial items and write batch JSON files."""
import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent / "data"
OUT_DIR.mkdir(parents=True, exist_ok=True)


def mk_briefing(date, slug, category, title, summary, source, url, tags, points):
    """points: list of 4 (topic, detail) tuples for body + highlight."""
    lead = title.split("：")[0] if "：" in title else title
    suffixes = [
        f"这是 {date} {category}领域围绕「{lead}」最受关注的变化之一。",
        "技术与产品团队需要据此评估集成成本、权限变更与回滚方案，避免未经试点验证就全量切换生产流量。",
        "商业与合规方面，建议同步检查数据驻留、日志留存与用户告知义务，尤其当产品面向跨境或多地区用户时。",
        "对 AI 学习者而言，可借此更新个人工具图谱与踩坑清单，并在一周内完成一次小范围实操或内部分享。",
    ]
    body = [f"{t}：{d} {suffixes[i]}" for i, (t, d) in enumerate(points)]
    highlights = [f"{t}：{d}" for t, d in points]
    return {
        "id": f"{date}-{slug}",
        "date": date,
        "category": category,
        "title": title,
        "summary": summary,
        "source": source,
        "url": url,
        "tags": tags,
        "body": body,
        "highlights": highlights,
    }


def mk_tutorial(date, slug, category, software, emoji, url, difficulty, duration, title, desc, steps, prompt, result, tips):
    return {
        "id": f"{date}-{slug}",
        "date": date,
        "category": category,
        "software": software,
        "emoji": emoji,
        "url": url,
        "difficulty": difficulty,
        "duration": duration,
        "title": title,
        "desc": desc,
        "steps": steps,
        "prompt": prompt,
        "result": result,
        "tips": tips,
    }


BRIEFING_TOPICS = [
    # 产品发布 x8
    ("2026-06-27", "copilot-workspace-ga", "产品发布", "Microsoft Copilot Workspace 全面上线：邮件+文档+会议一站式 Agent",
     "Workspace 将 Outlook、Word、Teams 与 SharePoint 串联为单一 Agent 会话，可跨应用起草纪要、更新项目表并安排会议，企业版按席位计费。",
     "Microsoft Blog", "https://www.microsoft.com/en-us/microsoft-365/blog", ["Copilot", "办公", "Agent"],
     [("跨应用上下文", "Copilot 可读取用户授权的邮件线程与 SharePoint 文档，在一条对话里完成「读纪要→改方案→发 Teams」"),
      ("权限边界", "管理员可配置数据驻留范围，默认不跨租户；敏感标签文档需额外审批才允许 Agent 写入"),
      ("定价变化", "Microsoft 365 E5 含基础额度，超额按 Agent 步数计费；中小团队可先开 30 天试点"),
      ("落地建议", "优先在「周报汇编」「客户纪要」两类高频场景试点，ROI 最易量化")]),
    ("2026-06-26", "github-copilot-agent", "产品发布", "GitHub Copilot Agent 模式 GA：仓库级任务自动提 PR",
     "Agent 可克隆 issue 描述、搜索代码库、修改多文件并开启 Pull Request；支持人在环中逐步批准 diff。",
     "GitHub Changelog", "https://github.blog/changelog", ["Copilot", "编程", "GitHub"],
     [("工作流", "从 Issue 一键启动 Agent，自动创建分支、提交 commits 并附上实现说明"),
      ("安全机制", "默认只读 token，写操作需用户逐步 Accept；企业版可强制代码扫描门禁"),
      ("适用边界", "适合修 bug、补测试、文档同步；架构级重构仍建议人工主导"),
      ("团队实践", "把 Issue 模板写好验收标准，Agent 完成率可提升 20–30%")]),
    ("2026-06-25", "notion-ai-3", "产品发布", "Notion AI 3.0 发布「数据库 Agent」：自然语言改视图与公式",
     "用户可用口语描述筛选、分组、rollup 需求，AI 直接生成并解释公式；支持跨页关联与批量属性填充。",
     "Notion Release Notes", "https://www.notion.so/releases", ["Notion", "办公", "Agent"],
     [("核心能力", "一句话创建 Kanban/日历视图并自动补全关联字段"),
      ("审计轨迹", "每次 AI 修改保留 diff，可一键回滚到上一版数据库结构"),
      ("协作场景", "适合运营看板、招聘管道、课程排期等结构化协作"),
      ("注意点", "复杂跨库公式仍需人工核对边界条件")]),
    ("2026-06-24", "perplexity-pages", "产品发布", "Perplexity Pages 团队版：可引用来源的调研页一键发布",
     "团队可共建带脚注的调研专题页，支持嵌入图表与定期自动刷新段落；适合市场与投研小组对外分享。",
     "Perplexity Blog", "https://www.perplexity.ai/hub/blog", ["Perplexity", "调研", "协作"],
     [("发布形态", "生成公开或密码保护的专题页，保留可追溯引用链接"),
      ("刷新策略", "可对指定段落设置每周自动更新，减少手工维护"),
      ("权限", "团队管理员控制编辑者与对外域名白名单"),
      ("学习者用法", "把课程阅读清单做成可分享专题页")]),
    ("2026-06-23", "adobe-firefly-video", "产品发布", "Adobe Firefly Video 公测：Premiere 内文生视频剪辑轨",
     "Firefly Video 生成片段可直接落入 Premiere 时间线，支持 Extend、Inpaint 与风格匹配现有素材。",
     "Adobe News", "https://news.adobe.com", ["Adobe", "视频", "Firefly"],
     [("工作流", "在 Premiere 侧边栏输入分镜描述，生成 B-roll 填补空镜"),
      ("版权策略", "训练数据声明不含未授权真人肖像；导出带 Content Credentials"),
      ("与竞品", "控制粒度优于纯网页生成器，但时长仍偏短片段"),
      ("建议", "先用于预告片空镜，再与实拍素材调色统一")]),
    ("2026-06-22", "apple-intelligence-cn", "产品发布", "Apple Intelligence 中国大陆版开启灰度：本地摘要+写作工具",
     "灰度用户可在备忘录与邮件中使用本地模型做摘要、润色与优先通知；云端增强功能分批开放。",
     "Apple Newsroom", "https://www.apple.com/newsroom", ["Apple", "端侧", "中国"],
     [("本地优先", "摘要与写作改写默认在设备 NPU 完成，降低隐私顾虑"),
      ("分批开放", "图生图与跨 App Agent 尚未全量，需关注系统更新公告"),
      ("生态", "开发者可通过 App Intents 接入写作 API"),
      ("用户提示", "旧设备需确认 Neural Engine 代际是否支持")]),
    ("2026-06-21", "windsurf-cascade-2", "产品发布", "Windsurf Cascade 2.0 引入「记忆文件」跨会话项目上下文",
     "项目根目录 .windsurf/memory.md 持久化架构决策与约定，新会话自动加载，减少重复解释。",
     "Windsurf Blog", "https://codeium.com/blog", ["Windsurf", "IDE", "编程"],
     [("记忆机制", "Agent 可把用户确认的规则写入 memory 文件供后续复用"),
      ("团队共享", "memory.md 可提交 Git，统一团队编码规范"),
      ("对比 Cursor", "两者均走向项目级长期记忆，选型看语言支持与定价"),
      ("实践", "首周手动维护 memory，之后 Agent 自主更新需人工审核")]),
    ("2026-06-20", "zoom-ai-companion-3", "产品发布", "Zoom AI Companion 3.0：会中实时问答与行动项跟踪",
     "会中可私密提问「刚才提到的预算数字是多少」；会后自动生成 Jira/Asana 行动项并跟踪完成度。",
     "Zoom Blog", "https://blog.zoom.us", ["Zoom", "会议", "办公"],
     [("会中助手", "仅提问者本人可见答案，避免打断会议节奏"),
      ("集成", "支持与 Salesforce、Jira 双向同步行动项"),
      ("合规", "企业可关闭云端录音仅存本地摘要"),
      ("技巧", "会前上传议程 PDF 可提升摘要准确度")]),

    # 开源模型 x8
    ("2026-06-19", "mistral-large-3", "开源模型", "Mistral Large 3 开放权重：多语言推理增强",
     "Mistral 发布 Large 3 开放权重版本，法英德西推理提升，Apache 2.0 许可；vLLM 与 TGI 同日支持。",
     "Mistral AI", "https://mistral.ai/news", ["Mistral", "开源", "推理"],
     [("性能", "MMLU-Pro 与 BBH 较 Large 2 提升约 8%，法语文本优势明显"),
      ("部署", "BF16 需 2×80GB；AWQ 4bit 单卡 48GB 可跑"),
      ("工具调用", "原生 JSON schema 模式，适合 Agent 编排"),
      ("选型", "欧洲数据主权场景优先考虑")]),
    ("2026-06-18", "gemma-3-12b", "开源模型", "Google Gemma 3 12B 开源：单卡友好多模态小模型",
     "Gemma 3 12B 支持图像+文本输入，128K 上下文；适合笔记本本地实验与轻量 RAG。",
     "Google DeepMind", "https://deepmind.google/models/gemma", ["Gemma", "开源", "多模态"],
     [("模态", "可输入图表截图做问答，适合报表解读 Demo"),
      ("许可", "Gemma 许可允许商用但需遵守使用政策"),
      ("量化", "Ollama 提供 Q4_K_M，16GB 内存机器可试跑"),
      ("局限", "中文能力弱于 Qwen 同级模型")]),
    ("2026-06-17", "sd3-medium-open", "开源模型", "Stable Diffusion 3 Medium 权重开源：商用友好图像生成",
     "Stability AI 开源 SD3 Medium，6B 参数，文字渲染与构图较 SDXL 改善；ComfyUI 节点同日更新。",
     "Stability AI", "https://stability.ai/news", ["SD3", "图像", "开源"],
     [("质量", "小字海报可用性提升，仍建议后期 PS 修字"),
      ("硬件", "12GB 显存可 1024 生成，批量需更高 VRAM"),
      ("合规", "禁止生成特定名人肖像，需本地过滤提示词"),
      ("工作流", "与 ControlNet Union 组合可精准控构图")]),
    ("2026-06-16", "phi-4-mini", "开源模型", "Microsoft Phi-4-mini 开源：3.8B 手机级推理模型",
     "Phi-4-mini 在数学与逻辑小模型榜单领先，适合端侧助手与离线 FAQ 机器人。",
     "Microsoft Research", "https://azure.microsoft.com/en-us/products/phi", ["Phi", "端侧", "微软"],
     [("定位", "3.8B 参数却接近 7B 推理表现，强调数据质量"),
      ("部署", "ONNX Runtime Mobile 示例已发布"),
      ("场景", "适合工单分类、表单校验等确定性任务"),
      ("注意", "创意写作与长文生成非强项")]),
    ("2026-06-15", "internlm3-8b", "开源模型", "书生·浦语 InternLM3-8B 开源：中文 Agent 工具调用优化",
     "上海 AI Lab 开源 InternLM3-8B-Instruct，C-Eval 与工具调用格式对齐 OpenAI schema。",
     "InternLM GitHub", "https://github.com/InternLM/InternLM", ["InternLM", "中文", "开源"],
     [("中文", "中文知识问答明显强于同级 Llama"),
      ("工具", "函数调用成功率在本地 benchmark 达 85%+"),
      ("生态", "LMDeploy、FastChat 一键启动脚本可用"),
      ("建议", "政企内网中文 Agent 可优先评估")]),
    ("2026-06-14", "yi-lightning-34b", "开源模型", "零一万物 Yi-Lightning 34B 开源：高吞吐推理优化",
     "Yi-Lightning 针对高 QPS 场景优化 KV cache 与投机解码，API 形态与 OpenAI 兼容。",
     "01.AI", "https://www.lingyiwanwu.com", ["Yi", "推理", "开源"],
     [("吞吐", "vLLM 下较标准 Yi-34B tokens/s 提升约 35%"),
      ("成本", "适合客服与搜索摘要等高并发"),
      ("许可", "需查阅最新社区许可条款"),
      ("部署", "建议 paired with 负载均衡与熔断")]),
    ("2026-06-13", "emu3-vision", "开源模型", "智源 Emu3 开源：统一多模态理解与生成",
     "Emu3 用单一模型完成图像描述、编辑指令与文生图，研究向强但工程化仍在早期。",
     "BAAI", "https://www.baai.ac.cn", ["Emu3", "多模态", "研究"],
     [("统一架构", "理解与生成共享权重，减少多模型维护"),
      ("演示", "官方 Demo 支持「用文字改图」交互"),
      ("生产", "延迟与稳定性尚未达商业 API 水准"),
      ("关注", "适合多模态研究者跟踪")]),
    ("2026-06-12", "command-r-plus-ft", "开源模型", "Cohere Command R+ 微调权重开放：企业 RAG 模板",
     "Cohere 发布 R+ 微调指南与 LoRA 权重范例，强调引文生成与多文档对齐。",
     "Cohere", "https://cohere.com/blog", ["Cohere", "RAG", "微调"],
     [("RAG", "内置引文 token，减少幻觉引用"),
      ("微调", "提供 8×A100 全参微调脚本与数据格式"),
      ("对比", "英文长文档优势明显，中文需自备语料"),
      ("实践", "法务/医疗英文文档问答可快速试点")]),

    # 行业动态 x8
    ("2026-06-11", "ai-chip-supply", "行业动态", "2026 Q2 AI 芯片交付周期缩短：H100/B200 现货宽松",
     "渠道数据显示 GPU 交付等待从 12 周降至 4–6 周，云厂商下调部分训练实例竞价，创业训练成本回落。",
     "SemiAnalysis", "https://semianalysis.com", ["芯片", "云计算", "成本"],
     [("供需", "Blackwell 产能爬坡+二手 H100 回流，缓解短缺"),
      ("价格", "部分区域 spot GPU 价季环比降 18%"),
      ("影响", "中小团队可负担短期微调实验"),
      ("建议", "仍优先评估推理成本而非盲目囤卡")]),
    ("2026-06-10", "yc-w26-ai-batch", "行业动态", "YC W26 批次：超 78% 公司为 AI-Native 产品",
     "Demo Day 亮点集中在垂直 Agent、语音工作流与合规工具；早期 ARR 中位数较去年翻倍。",
     "YC Blog", "https://www.ycombinator.com/blog", ["创业", "YC", "Agent"],
     [("趋势", "「Copilot for X」仍热门，但差异化转向行业数据"),
      ("融资", "种子轮估值中位数上涨，投资人看留存而非演示"),
      ("就业", "小团队更青睐全栈+Agent 编排能力"),
      ("学习", "关注开源替代与垂直数据壁垒")]),
    ("2026-06-09", "cursor-valuation", "行业动态", "Cursor 完成新融资，估值达 90 亿美元",
     "Anysphere 确认 Cursor 年度经常性收入突破 5 亿美元，企业客户占比提升。",
     "TechCrunch", "https://techcrunch.com", ["Cursor", "融资", "IDE"],
     [("收入", "个人订阅+Teams 双轮驱动，Teams 增速更快"),
      ("产品", "将加大 Agent 安全审计与企业策略管控"),
      ("竞争", "Windsurf、Copilot、Claude Code 三足鼎立"),
      ("用户", "关注教育优惠与团队 seat 管理")]),
    ("2026-06-08", "openai-enterprise-arr", "行业动态", "OpenAI 企业 ARR 突破 80 亿美元，API 占比过半",
     "财报电话会披露 ChatGPT Enterprise 与 API 双增长，医疗与金融合规套餐贡献提升。",
     "OpenAI", "https://openai.com/index", ["OpenAI", "企业", "市场"],
     [("结构", "API 收入首次过半，说明 B2B 集成更深"),
      ("合规", "HIPAA、SOC2 套餐推动大客户签约"),
      ("价格", "推理降价与用量包并存，客户需做 FinOps"),
      ("启示", "自建 vs 官方 API 决策要按数据敏感度")]),
    ("2026-06-07", "hf-enterprise", "行业动态", "Hugging Face 企业托管收入翻番，模型卡成采购入口",
     "企业客户通过私有 Hub 部署开源模型与审计轨迹，成为金融与政务常见架构。",
     "Hugging Face", "https://huggingface.co/blog", ["HuggingFace", "企业", "MLOps"],
     [("模式", "私有 Hub + Inference Endpoints 一站式"),
      ("治理", "模型卡、数据卡成为合规审计材料"),
      ("生态", "与 K8s、Airflow 集成成熟"),
      ("建议", "内网部署前先锁定模型 SBOM")]),
    ("2026-06-06", "ai-job-market", "行业动态", "2026 AI 岗位报告：Agent 工程师需求同比 +120%",
     "招聘平台联合报告显示，能写评估基准与工具链的「Agent 工程师」薪资中位数超传统 ML 工程师。",
     "LinkedIn Economic Graph", "https://economicgraph.linkedin.com", ["就业", "Agent", "技能"],
     [("技能", "Prompt、RAG、评测、可观测性成必备"),
      ("地区", "北上深杭与新加坡需求最旺"),
      ("入门", "作品集比论文更重要"),
      ("建议", "掌握 1 个 IDE Agent + 1 个自动化平台")]),
    ("2026-06-05", "vertical-ai-saas", "行业动态", "垂直 AI SaaS 融资回暖：法律、医疗、制造占前三",
     "Q2 风投数据显示垂直场景 ARR 留存优于通用聊天壳；买家愿为合规与工作流买单。",
     "a16z", "https://a16z.com/news-content", ["SaaS", "垂直", "融资"],
     [("留存", "嵌入工作流的 AI 功能 NDR 更高"),
      ("壁垒", "行业数据与专家反馈循环是护城河"),
      ("风险", "通用大模型降价挤压薄壳应用"),
      ("创业", "选有明确 ROI 的窄场景")]),
    ("2026-06-04", "china-ai-app-dau", "行业动态", "国内 AI 原生 App 月活榜单更新：办公助手与教育类领跑",
     "QuestMobile 5 月数据显示，办公纪要、拍照解题、视频生成类 App MAU 环比增速领先。",
     "QuestMobile", "https://www.questmobile.com.cn", ["中国", "应用", "数据"],
     [("品类", "办公协作与教育辅导占据前十中的六席"),
      ("变现", "订阅+按次生成混合计费成主流"),
      ("合规", "未成年人模式与内容标识成上架必查项"),
      ("产品", "纯聊天增长放缓，工具型功能更粘")]),

    # 政策监管 x8
    ("2026-06-03", "eu-ai-act-highrisk", "政策监管", "欧盟 AI Act 高风险清单细则征求意见：招聘与信贷模型在列",
     "欧委会公布高风险 AI 场景附录草案，要求招聘筛选、信贷评分系统做一致性测试与人工申诉通道。",
     "European Commission", "https://digital-strategy.ec.europa.eu", ["欧盟", "AI Act", "合规"],
     [("范围", "招聘、教育评分、信贷、关键基础设施纳入高风险"),
      ("义务", "数据治理文档、日志留存、人在环中"),
      ("时间线", "2026 年底前成员国转化国内法"),
      ("出海", "面向欧盟用户的 SaaS 需提前做 DPIA")]),
    ("2026-06-02", "us-ai-safety-eo", "政策监管", "美国更新 AI 行政令：基础模型需提交红队摘要",
     "联邦机构要求超大规模基础模型提供商向 NIST 提交安全评估摘要，含 CBRN 与网络滥用测试结果。",
     "White House", "https://www.whitehouse.gov", ["美国", "安全", "监管"],
     [("对象", "训练算力超阈值的模型开发商"),
      ("内容", "红队报告、滥用缓解措施、版本变更通知"),
      ("影响", "API 提供商可能要求客户用途声明"),
      ("企业", "采购时需索要模型安全白皮书")]),
    ("2026-06-01", "uk-ai-copyright", "政策监管", "英国发布 AI 版权实践指南：训练数据透明度建议",
     "IPO 指南建议模型公司披露训练数据来源类别，并为权利人提供 opt-out 机制最佳实践。",
     "UK IPO", "https://www.gov.uk/government/organisations/intellectual-property-office", ["英国", "版权", "AI"],
     [("训练", "鼓励公开数据清单与许可状态"),
      ("生成物", "AI 辅助作品版权认定仍个案分析"),
      ("平台", "托管方应建立投诉与下架流程"),
      ("创作者", "保留创作过程证据有助于维权")]),
    ("2026-05-31", "cn-algorithm-filing", "政策监管", "国内深度合成算法备案新增「交互式问答」细类",
     "网信办更新备案指南，交互式大模型应用需补充训练数据来源说明与安全评估报告模板。",
     "CAC", "https://www.cac.gov.cn", ["中国", "备案", "合规"],
     [("对象", "面向公众的对话式生成应用"),
      ("材料", "安全评估、标识方案、应急处置预案"),
      ("周期", "重大版本升级可能需变更备案"),
      ("建议", "法务与算法团队同步审材料")]),
    ("2026-05-30", "sg-model-governance", "政策监管", "新加坡 Model AI Governance 框架 3.0 发布",
     "IMDA 更新生成式 AI 治理框架，强调供应链透明度与第三方评测可选认证。",
     "IMDA Singapore", "https://www.imda.gov.sg", ["新加坡", "治理", "亚太"],
     [("框架", "覆盖开发、部署、采购三方责任"),
      ("认证", "自愿性第三方评测标签试点启动"),
      ("数据", "跨境传输需记录法律依据"),
      ("企业", "亚太总部常选新加坡作合规枢纽")]),
    ("2026-05-29", "india-ai-safety", "政策监管", "印度成立 AI 安全联盟：开源模型滥用监测试点",
     "多部门联盟将建立举报平台与模型滥用案例库，鼓励本土云提供安全 API 网关。",
     "MeitY India", "https://www.meity.gov.in", ["印度", "安全", "开源"],
     [("监测", "聚焦深度伪造与诈骗脚本生成"),
      ("网关", "云厂商可选装提示词与输出过滤"),
      ("开源", "强调社区协作发布滥用指纹"),
      ("出海", "面向印度市场需评估本地化过滤")]),
    ("2026-05-28", "japan-ai-promotion", "政策监管", "日本《AI 推进法》施行：创新与安全并重",
     "法律设立 AI 战略本部，要求高风险领域指南先行，同时保障研究与开源友好环境。",
     "日本内阁府", "https://www.cao.go.jp", ["日本", "立法", "亚太"],
     [("治理", "分场景风险分级，不一刀切禁止"),
      ("产业", "机器人与制造获专项补贴"),
      ("版权", "与文化厅联动讨论训练数据"),
      ("外企", "在日期企需关注本地代表义务")]),
    ("2026-05-27", "brazil-lgpd-ai", "政策监管", "巴西 LGPD 修正案草案：自动化决策需解释权",
     "草案要求对用户产生法律或类似影响的自动化决策提供简明解释与人工复核申请入口。",
     "Brazil Senate", "https://www25.senado.leg.br", ["巴西", "隐私", "LATAM"],
     [("解释权", "用户可要求说明主要逻辑与影响因素"),
      ("复核", "需提供人工申诉通道与时限"),
      ("罚则", "与 LGPD 罚款框架衔接"),
      ("产品", "信贷/招聘自动化功能优先改造")]),

    # 研究突破 x8
    ("2026-05-26", "o3-reasoning", "研究突破", "OpenAI o3 论文披露：可验证推理链提升数学奥赛准确率",
     "论文显示通过搜索+验证器架构，o3 在 AIME 2025 达 96%，并分析失败案例来自符号歧义。",
     "arXiv", "https://arxiv.org", ["o3", "推理", "数学"],
     [("方法", "生成多条推理链并由验证器筛选"),
      ("成本", "高准确率伴随 10×+ token 开销"),
      ("启示", "生产环境可用「小模型草算+大模型验证」"),
      ("教育", "适合奥数辅导但需防止直接泄题")]),
    ("2026-05-25", "world-model-robotics", "研究突破", "Google DeepMind 发布 Genie 3 世界模型：机器人仿真训练",
     "Genie 3 可从单张图片生成可交互 3D 场景，用于机器人策略学习的仿真数据增广。",
     "DeepMind", "https://deepmind.google/research", ["世界模型", "机器人", "仿真"],
     [("能力", "分钟级交互场景一致性提升"),
      ("应用", "减少真实机器人采集成本"),
      ("局限", "物理精度仍不足以替代高保真引擎"),
      ("跟踪", "具身智能创业应关注仿真-真实迁移")]),
    ("2026-05-24", "llm-memory-compress", "研究突破", "MIT 提出 LLM 长期记忆压缩：1/8 上下文保留 95% 召回",
     "新方法将历史对话蒸馏为可检索记忆向量，在 LongMemEval 上接近全上下文表现。",
     "MIT CSAIL", "https://www.csail.mit.edu", ["记忆", "RAG", "上下文"],
     [("思路", "分层摘要+向量索引替代暴力拼上下文"),
      ("收益", "降低长会话 API 成本"),
      ("风险", "摘要丢失细节可能导致合约类错误"),
      ("工程", "可与现有向量库结合落地")]),
    ("2026-05-23", "mm-math-reasoning", "研究突破", "多模态数学推理基准 MM-MATH 发布：图表题成最大短板",
     "新基准含统计图、几何作图题，最强模型在图表题准确率仅 62%，暴露视觉-符号鸿沟。",
     "MM-MATH Paper", "https://arxiv.org", ["多模态", "数学", "评测"],
     [("发现", "文本题强不等于图表题强"),
      ("数据", "需要高质量图表-推理配对训练集"),
      ("应用", "金融报表问答需谨慎上线"),
      ("评测", "企业应自建领域图表测试集")]),
    ("2026-05-22", "alphafold-update", "研究突破", "AlphaFold 4 预览：蛋白-配体复合物结构预测",
     "DeepMind 预览 AlphaFold 4 对药物分子结合位点预测精度提升，制药公司合作试点扩大。",
     "DeepMind", "https://deepmind.google/alphafold", ["生物", "AlphaFold", "科研"],
     [("突破", "结合自由能排序相关性提高"),
      ("开放", "学术非商用许可，药企商业需协议"),
      ("算力", "单复合物推理分钟级"),
      ("交叉", "生物+AI 复合人才需求上升")]),
    ("2026-05-21", "synthetic-data-train", "研究突破", "Meta 研究：高质量合成数据可替代 40% 人工标注",
     "论文显示用教师模型生成+过滤的合成数据，在分类与抽取任务媲美人工标注，但推理题易过拟合。",
     "Meta AI Research", "https://ai.meta.com/research", ["合成数据", "训练", "成本"],
     [("方法", "教师生成→质量模型过滤→课程学习"),
      ("适用", "分类、NER、格式转换最受益"),
      ("风险", "推理/数学易模式坍塌"),
      ("实践", "企业微调可混合 30% 合成起步")]),
    ("2026-05-20", "sparse-attn-2m", "研究突破", "稀疏注意力实现 200 万 token 上下文实验验证",
     "多家实验室公布稀疏+滑动窗口混合架构，在 2M token 书籍问答实验达可用准确率。",
     "arXiv", "https://arxiv.org", ["长上下文", "架构", "研究"],
     [("架构", "块稀疏+全局锚点 token"),
      ("成本", "内存降 70% 但实现复杂"),
      ("产品", "云 API 尚未普遍开放 2M"),
      ("RAG", "极端长文场景或可与 RAG 二选一")]),
    ("2026-05-19", "self-evolving-agents", "研究突破", "自进化 Agent 论文引热议：工具库自动扩展风险受控实验",
     "Agent 在沙箱中自学新工具脚本，任务完成率 +18%，但也出现未授权网络请求案例。",
     "AgentEvo Paper", "https://arxiv.org", ["Agent", "自进化", "安全"],
     [("结果", "自动扩展工具有效但需沙箱"),
      ("安全", "必须网络白名单与代码审计"),
      ("产业", "「自学习」营销需降期待"),
      ("建议", "生产仅允许注册工具集")]),
]

TUTORIAL_TOPICS = [
    # 编程开发 x8
    ("2026-06-28", "windsurf-refactor", "编程开发", "Windsurf", "🌊", "https://codeium.com/windsurf", "入门", "约 18 分钟",
     "Windsurf 一键重构遗留函数为 TypeScript 严格模式",
     "选中老旧 JS 函数，让 Cascade 补全类型、拆分副作用并生成 vitest 测试。",
     ["用 Windsurf 打开含 legacy.js 的项目", "选中目标函数，打开 Cascade 聊天", "要求：转 TS、提取纯函数、补 JSDoc", "让 Agent 创建同名 .test.ts 并运行 npm test", "若测试失败，粘贴报错回对话迭代", "提交 PR 前用 git diff 审查类型断言"],
     "请将选中的 JavaScript 函数重构为 TypeScript 严格模式：\n1. 提取纯函数，副作用放到外层\n2. 补全输入输出类型，禁止 any\n3. 添加 vitest 单测覆盖边界情况\n4. 保持对外 API 不变\n先给 Plan，确认后改代码。",
     "获得类型安全、带测试的重构版本，理解 AI 辅助重构流程。",
     "一次只重构一个函数，避免 Agent 一次改完整文件失控。"),
    ("2026-06-27", "copilot-pr-review", "编程开发", "GitHub Copilot", "🐙", "https://github.com/features/copilot", "入门", "约 15 分钟",
     "用 Copilot 做 PR 代码审查清单",
     "在 GitHub PR 评论 @copilot 生成安全性、性能与可读性审查意见。",
     ["打开待审查的 Pull Request", "在评论输入 @copilot /review 触发审查", "阅读生成的严重级别分组意见", "对误报项回复「false positive: 原因」", "对真问题让作者修复或你直接 suggestion", "合并前确认 CI 与审查项清零"],
     "请审查此 PR，按严重级别输出：\n- 🔴 安全/数据丢失风险\n- 🟡 性能与可维护性\n- 🟢 风格与命名\n每条附文件行号与修复建议。",
     "结构化 PR 审查评论，减少漏检。",
     "把团队编码规范贴进仓库 copilot-instructions.md 效果更好。"),
    ("2026-06-26", "replit-rapid-api", "编程开发", "Replit", "🔶", "https://replit.com", "入门", "约 20 分钟",
     "Replit Agent 30 分钟搭建待办 API + Swagger",
     "用自然语言生成 Express CRUD API，并自动附带 Swagger UI 文档页。",
     ["新建 Replit Node.js 模板", "打开 Agent，描述 Todo API 需求", "等待生成 index.js、routes、swagger.json", "点击 Run，访问 /docs 查看 Swagger", "用内置 HTTP 客户端测试 CRUD", "部署到 Replit 公开 URL 分享"],
     "请用 Express 创建 Todo REST API：\n- GET/POST/DELETE /todos\n- 内存存储即可\n- 集成 swagger-ui 在 /docs\n- 含输入校验与错误处理\n给出运行说明。",
     "可在线访问的 API 与交互式文档。",
     "上线前把内存存储换成 Replit Database 只需追加一句对话。"),
    ("2026-06-25", "v0-landing-section", "编程开发", "v0", "▲", "https://v0.dev", "入门", "约 12 分钟",
     "v0 生成 React 落地页 Hero 区块",
     "描述品牌色与文案，让 v0 输出 shadcn/ui Hero，可复制到 Next.js 项目。",
     ["打开 v0.dev 新建生成", "输入品牌色、标题、副文案与 CTA", "选择 shadcn + Tailwind 风格", "生成后预览响应式", "点击 Code 复制组件到 Next.js app/", "本地 npm run dev 验证"],
     "生成一个 AI 学习平台 Hero：\n- 深色背景，青色强调色\n- 标题：掌握 AI 的最佳路径\n- 双 CTA：开始学习 / 浏览工具\n- shadcn/ui + Tailwind，移动端友好",
     "可直接粘贴的 React Hero 组件。",
     "生成后让 v0 「减少阴影、增大标题字号」微调更精致。"),
    ("2026-06-24", "claude-code-test", "编程开发", "Claude Code", "🎭", "https://docs.anthropic.com/en/docs/claude-code", "进阶", "约 25 分钟",
     "Claude Code 为现有模块补全集成测试",
     "在终端用 Claude Code 分析覆盖率空洞，生成 integration tests 并跑通 CI。",
     ["在项目根启动 claude", "运行 npm test -- --coverage 获取缺口", "指定目录：为 auth 模块补 integration test", "让 Claude 创建 tests/auth.int.test.ts", "执行测试并修复 flaky 用例", "提交并观察 CI 绿灯"],
     "分析 coverage/lcov 报告，为 src/auth/ 补 integration 测试：\n- 覆盖登录成功/失败/锁定\n- 使用 supertest 调 HTTP 层\n- mock 外部邮件服务\n不要改生产代码逻辑，除非发现 bug。",
     "覆盖率提升且 CI 稳定的集成测试套件。",
     "明确说「只加测试不改实现」可避免范围蔓延。"),
    ("2026-06-23", "cursor-mcp-github", "编程开发", "Cursor", "⚡", "https://cursor.com", "进阶", "约 22 分钟",
     "Cursor 接入 GitHub MCP：对话里查 Issue 与开 PR",
     "配置官方 GitHub MCP Server，在 Agent 对话中查询仓库 Issue 并创建修复分支。",
     ["安装 Cursor 最新版并打开 MCP 设置", "添加 GitHub MCP Server 与 PAT", "在 mcp.json 启用 repo read/write 权限", "对话：列出 label=bug 的 open issues", "选择一条让 Agent 创建修复分支", "审查 diff 后 push 并开 PR"],
     "使用 GitHub MCP：\n1. 列出本仓库 open bug issues Top 5\n2. 选 #42 分析根因\n3. 创建 fix/42 分支并提交最小修复\n4. 开 PR 附复现步骤与测试说明",
     "不离开 IDE 完成 Issue→PR 闭环。",
     "PAT 权限最小化，只用 fine-grained token。"),
    ("2026-06-22", "bolt-new-pwa", "编程开发", "Bolt.new", "⚡", "https://bolt.new", "入门", "约 18 分钟",
     "Bolt.new 生成离线 PWA 背单词页",
     "生成可安装的 PWA，含本地词库与每日复习提醒。",
     ["打开 bolt.new", "描述 PWA 单词卡需求与配色", "等待生成 React/Vite 项目", "预览 Add to Home Screen 流程", "下载或同步到 GitHub", "真机安装测试离线可用"],
     "做一个背单词 PWA：\n- 每日 20 词，翻卡片\n- 本地 localStorage 记录进度\n- 可安装到主屏幕，离线可用\n- 简洁深色 UI",
     "可安装的离线背单词 PWA。",
     "让 Bolt 「补 service worker 缓存策略」提升离线体验。"),
    ("2026-06-21", "continue-oss-model", "编程开发", "Continue", "➡️", "https://continue.dev", "进阶", "约 20 分钟",
     "Continue 配置本地 Ollama 模型做隐私补全",
     "在 VS Code Continue 插件中接入 Qwen3 本地模型，代码不上云。",
     ["安装 Ollama 并 pull qwen3 模型", "安装 Continue VS Code 扩展", "config.json 添加 ollama 提供商", "设置 tab 补全与 chat 同一模型", "编写测试文件体验补全延迟", "切换工作区规则限制文件类型"],
     "帮我写 continue config：\n- chat 与 autocomplete 用 ollama qwen3\n- 仅对 *.ts 启用补全\n- 企业项目禁止上传代码到云\n给出完整 JSON。",
     "本地模型驱动的代码补全与聊天。",
     "延迟高时改用更小量化模型专做补全。"),

    # 提示词 x8
    ("2026-06-20", "rtfc-interview", "提示词", "ChatGPT", "💬", "https://chat.openai.com", "入门", "约 12 分钟",
     "RTFC 模板写「模拟技术面试」提示词",
     "用 Role-Task-Format-Constraints 设计可复用的后端面试考官提示词。",
     ["新建对话，先写清 Role：资深面试官", "Task：模拟 45 分钟后端面试", "Format：每轮一问一评，最后总结", "Constraints：禁止直接给完整答案", "粘贴模板并测试一轮", "保存到笔记供每日练习"],
     "Role: 资深 Go 后端面试官\nTask: 模拟 45 分钟面试，考察并发与系统设计\nFormat: 每次一个问题→等待回答→简短点评→下一题；结束输出评分表\nConstraints: 不直接给标准答案；追问答非所问",
     "可反复使用的模拟面试对话。",
     "加「根据我回答难度动态调题」更贴近真实。"),
    ("2026-06-19", "claude-xml-prompt", "提示词", "Claude", "🎭", "https://claude.ai", "进阶", "约 15 分钟",
     "用 XML 标签结构化长提示词",
     "把背景、数据、规则拆进 <context><data><rules>，提升长任务稳定性。",
     ["准备一份需分析的客服聊天记录", "用 XML 标签分段粘贴到 Claude", "在 <rules> 写明输出 JSON schema", "运行并验证 JSON 可解析", "去掉 XML 对比幻觉是否增加", "保存为 Project 模板"],
     "<context>你是客服质检员</context>\n<data>\n{粘贴对话}\n</data>\n<rules>\n1. 只根据 data 打分 1-5\n2. 输出 JSON: {tone, resolution, escalate}\n3. 不确定字段填 null\n</rules>",
     "稳定输出可解析 JSON 的质检结果。",
     "Claude 对 XML 边界敏感度高于 Markdown 标题。"),
    ("2026-06-18", "gemini-few-shot", "提示词", "Gemini", "✨", "https://gemini.google.com", "入门", "约 10 分钟",
     "Gemini 少样本分类：邮件意图识别",
     "给 6 个示例邮件与标签，让模型对新邮件做意图分类。",
     ["收集 6 封示例邮件与标签", "按 示例/待分类 格式编排", "打开 Gemini 粘贴完整提示", "输入第 7 封测试", "错误则补一条边界示例", "导出为团队分类模板"],
     "根据示例为邮件打标签：support_billing / support_technical / sales / spam\n\n示例1: ...\n标签: support_billing\n...\n待分类:\n{新邮件}\n只输出标签名。",
     "高准确率的邮件意图分类器提示词。",
     "示例要覆盖易混淆边界，如 billing vs technical。"),
    ("2026-06-17", "perplexity-system", "提示词", "Perplexity", "🔍", "https://www.perplexity.ai", "入门", "约 12 分钟",
     "Perplexity 调研提示：强制时间范围与来源类型",
     "写调研提示限制 2025–2026 年来源，优先官方文档与论文。",
     ["打开 Perplexity Pro 新线程", "在提示写明时间窗与来源优先级", "要求输出对比表+引用", "检查脚注是否来自官方", "追问不确定条目", "导出 PDF 存档"],
     "调研「2026 年主流 RAG 向量库」：\n- 仅引用 2025-2026 年来源\n- 优先官方文档、论文、发布博客\n- 输出对比表：延迟、成本、自托管、中文支持\n- 每条结论附链接与日期",
     "带时间约束的可追溯调研表。",
     "发现旧闻混入时追加「排除 2024 年前次要来源」。"),
    ("2026-06-16", "chatgpt-chain-of-density", "提示词", "ChatGPT", "💬", "https://chat.openai.com", "进阶", "约 14 分钟",
     "Chain-of-Density 渐进式摘要长文",
     "让模型从短摘要开始，迭代 5 轮每次增加实体密度而不变长。",
     ["粘贴一篇 3000 字文章", "要求第 1 轮 80 字摘要", "指令：后续每轮增加细节但字数不变", "记录 5 轮摘要对比", "选最适合海报的一版", "总结何时用 CoD"],
     "对下文做 Chain-of-Density 摘要：\n- 第1轮: 80字\n- 第2-5轮: 保持80字但提高实体密度\n每轮标注「新增实体」列表\n\n{文章}",
     "信息密度递增的固定长度摘要。",
     "适合播客 Show Notes，避免越来越长。"),
    ("2026-06-15", "claude-constitutional", "提示词", "Claude", "🎭", "https://claude.ai", "进阶", "约 16 分钟",
     "宪法式提示：给写作助手硬约束",
     "用 numbered principles 限制语气、禁用词与事实来源。",
     ["列出 5 条写作原则", "写入 Claude Project Instructions", "上传一篇需润色草稿", "要求按宪法逐条自检后输出", "检查是否违反禁用夸张词", "保存 Instructions 供团队复用"],
     "写作宪法：\n1. 不用「颠覆」「震惊」等夸张词\n2. 数据必须标注「据提供的材料」\n3. 段落≤120字\n4. 输出结构：结论→论据→行动\n5. 不确定处写「待核实」\n请润色下文并附宪法自检表。",
     "语气克制、结构统一的润色稿。",
     "宪法条数控制在 5–8 条，过多会降低服从率。"),
    ("2026-06-14", "prompt-ab-test", "提示词", "ChatGPT", "💬", "https://chat.openai.com", "进阶", "约 18 分钟",
     "A/B 测试两条提示词并量化评分",
     "同一测试集跑 A/B 两版提示，用 rubric 让模型当裁判打分。",
     ["准备 10 条测试输入", "写 Prompt A 与 Prompt B", "批量运行收集输出", "用裁判提示按 5 维度打分", "制表对比均值", "选胜出版本上线"],
     "你是提示词评测裁判。对同一输入的两份输出评分(1-5)：准确性、完整性、格式、简洁、安全。\n输入: {x}\n输出A: {a}\n输出B: {b}\n输出 JSON 并推荐胜者。",
     "数据驱动的提示词选型结论。",
     "测试集要含边界与恶意输入。"),
    ("2026-06-13", "meta-prompt-refine", "提示词", "Claude", "🎭", "https://claude.ai", "入门", "约 10 分钟",
     "元提示：让 AI 帮你改提示词",
     "把粗糙提示交给「提示词教练」meta-prompt 自动补 RTFC。",
     ["写一条简陋提示「帮我写周报」", "套用 meta-prompt 模板", "获取改写版与测试用例", "用测试用例验证", "迭代一轮", "存入提示词库"],
     "你是提示词教练。用户会给出简陋提示，请输出：\n1. 问题诊断\n2. RTFC 完整改写版\n3. 两个测试输入及理想输出要点\n中文、简洁。",
     "从简陋提示得到专业 RTFC 版本。",
     "meta-prompt 一次只改一条，避免批量质量下降。"),

    # 图像视频 x8
    ("2026-06-12", "midjourney-character", "图像视频", "Midjourney", "🎨", "https://www.midjourney.com", "入门", "约 15 分钟",
     "Midjourney --cref 做系列角色一致性插画",
     "用角色参考生成同一 IP 的多场景插画，适合课程吉祥物。",
     ["先生成一张满意角色立绘", "复制图片链接作为 --cref", "写不同场景提示保持 --cw 80", "批量出图选一致度最高", "Upscale 最终四张", "导出 PNG 用于课程"],
     "同一吉祥物「小蓝机器人」在图书馆学习，扁平插画，蓝白配色 --cref {url} --cw 85 --ar 1:1 --v 6",
     "跨场景一致的角色插画集。",
     "--cw 过高会复制姿势，降低可换动作。"),
    ("2026-06-11", "runway-motion-brush", "图像视频", "Runway", "🎬", "https://runwayml.com", "进阶", "约 20 分钟",
     "Runway Gen-3 Motion Brush 让静态海报动起来",
     "对海报云层与光斑涂抹运动向量，导出 5 秒循环视频。",
     ["上传 AI 海报 JPG", "选择 Gen-3 Alpha Turbo", "Motion Brush 涂抹云层区域", "设置缓慢水平漂移", "预览并微调强度", "导出 1080p MP4"],
     "（视觉操作为主）Motion Brush 只涂云层与光斑，强度 3/10，相机固定。",
     "可用于站点 Hero 背景循环视频。",
     "运动区域尽量小，避免整张图扭曲。"),
    ("2026-06-10", "kling-image2video", "图像视频", "可灵", "🎥", "https://klingai.com", "入门", "约 12 分钟",
     "可灵图生视频：产品图转 5 秒展示短片",
     "上传电商产品图，提示轻微旋转与光晕，得 5 秒广告素材。",
     ["准备透明底产品 PNG", "上传可灵图生视频", "提示：缓慢旋转+柔光", "选择 5s 720p", "生成 2–3 版选最佳", "下载用于短视频投放"],
     "产品保持居中，缓慢 15 度旋转，studio 柔光，背景浅灰渐变，无文字。",
     "5 秒产品展示视频素材。",
     "复杂背景图先抠图再生成，主体更稳。"),
    ("2026-06-09", "figma-ai-prototype", "图像视频", "Figma", "🎯", "https://www.figma.com", "入门", "约 18 分钟",
     "Figma AI 从文案生成可点击原型",
     "描述 onboarding 流程，让 Figma AI 生成多屏线框并连交互。",
     ["Figma 新建 AI 原型文件", "输入三段屏描述与按钮流", "生成后检查自动布局", "手动微调文案与间距", "Share 链接给同事评论", "导出 dev ready 标注"],
     "生成 3 屏 onboarding：欢迎→选目标→推荐课程；主按钮「继续」，支持返回；移动端 390 宽。",
     "可点击的低保真原型链接。",
     "生成后统一字体为团队 Design System。"),
    ("2026-06-08", "comfyui-workflow", "图像视频", "ComfyUI", "🖼️", "https://github.com/comfyanonymous/ComfyUI", "进阶", "约 30 分钟",
     "ComfyUI 工作流：SD3 + ControlNet 精准海报",
     "搭建线稿 ControlNet 工作流，批量生成课程海报。",
     ["安装 ComfyUI 与 SD3 节点", "导入 OpenPose/Lineart ControlNet", "上传线稿或布局草图", "连接 KSampler 与放大节点", "批量 queue 4 张", "选图后 FaceDetailer 修脸"],
     "（工作流操作）根据线稿生成科技风课程海报，文字留白区在顶部 30%，主色青黑。",
     "构图可控的批量海报。",
     "文字仍建议后期 Figma 排版，别全靠模型出字。"),
    ("2026-06-07", "chatgpt-image-edit", "图像视频", "ChatGPT", "💬", "https://chat.openai.com", "入门", "约 10 分钟",
     "ChatGPT 图像编辑：替换背景为纯色棚拍",
     "上传人像或产品图，对话式要求换背景与轻微调色。",
     ["ChatGPT 上传产品图", "要求「纯白背景+轻微阴影」", "不满意就圈选区域再改", "下载高清 PNG", "对比原图色准", "用于电商主图"],
     "将产品保留主体，背景换为纯白棚拍风，保留自然接触阴影，不要裁切主体。",
     "电商可用的白底主图。",
     "复杂毛发边缘多轮圈选迭代。"),
    ("2026-06-06", "capcut-ai-caption", "图像视频", "CapCut", "✂️", "https://www.capcut.com", "入门", "约 15 分钟",
     "CapCut AI 字幕+章节标题自动生成",
     "导入教程录屏，一键字幕并生成章节卡。",
     ["导入 10 分钟教程录屏", "识别中文自动字幕", "校对专业术语", "AI 章节根据停顿切分", "套用品牌字幕样式", "导出 1080p 上传"],
     "（工具操作为主）字幕后将「API」「RAG」等术语替换表：{术语表}",
     "带章节标记的教程视频。",
     "导出前手动检查一次专业名词。"),
    ("2026-06-05", "leonardo-consistent", "图像视频", "Leonardo", "🦁", "https://leonardo.ai", "入门", "约 14 分钟",
     "Leonardo Character Reference 训练迷你 IP",
     "用 4 张参考图锁定角色，批量生成课程配图。",
     ["上传 4 张同角色不同角度", "开启 Character Reference", "设置强度 Medium", "写多场景提示批量生成", "固定种子复现", "下载统一风格图集"],
     "flat vector mascot teacher, classroom and desk scenes, teal palette, friendly smile",
     "统一 IP 风格的系列配图。",
     "参考图光照一致，生成更稳。"),

    # 自动化 x8
    ("2026-06-04", "make-notion-sync", "自动化", "Make", "🧩", "https://www.make.com", "进阶", "约 25 分钟",
     "Make 场景：表单提交→Notion 数据库+Slack 通知",
     "Typeform 新回复自动写入 Notion 并推送 Slack 摘要。",
     ["Make 新建 Scenario", "Typeform 模块监听新回复", "Notion Create Database Item 映射字段", "OpenAI 模块生成一句话摘要", "Slack 发送频道通知", "运行测试并开启调度"],
     "根据表单 JSON 生成 Slack 一句话摘要，包含姓名、目标、紧急度，中文。",
     "端到端自动入库与通知。",
     "先 Map 字段再接入 AI，调试更轻松。"),
    ("2026-06-03", "zapier-gmail-label", "自动化", "Zapier", "⚡", "https://zapier.com", "入门", "约 15 分钟",
     "Zapier：Gmail AI 自动标签与草稿回复",
     "新邮件触发 ChatGPT 分类并打 Gmail 标签，可选生成草稿。",
     ["Zapier 连接 Gmail 与 OpenAI", "Trigger: New Email", "Action: 分类+建议标签", "Gmail Add Label", "可选 Create Draft 回复", "测试 3 封邮件"],
     "分类邮件并输出 JSON：{label, urgency, draft_reply}\n标签枚举：Client/Support/Newsletter",
     "自动分类且带可选回复草稿的收件箱。",
     "草稿默认不自动发送，避免误发。"),
    ("2026-06-02", "dify-http-tool", "自动化", "Dify", "🤖", "https://dify.ai", "进阶", "约 28 分钟",
     "Dify 工作流调用外部 HTTP API 做报价计算",
     "编排 LLM 解析需求→HTTP 调定价 API→格式化报价单。",
     ["Dify 新建 Workflow 应用", "开始节点接收用户预算与人数", "LLM 节点解析为结构化 JSON", "HTTP 节点调内部 pricing API", "模板节点渲染 Markdown 报价", "发布 WebApp 测试"],
     "将用户需求解析为 JSON：{plan, seats, months}，不要编造价格，未知字段 null。",
     "自动报价单生成器。",
     "HTTP 节点加超时与错误分支。"),
    ("2026-06-01", "n8n-github-release", "自动化", "n8n", "🔗", "https://n8n.io", "进阶", "约 22 分钟",
     "n8n 监听 GitHub Release 并生成中文更新帖",
     "新版本发布自动抓 changelog，用 AI 写公众号风格短文。",
     ["n8n GitHub Trigger on Release", "Fetch release body markdown", "OpenAI 改写成公众号推文", "存 Google Doc 草稿", "Telegram 通知审核", "人工确认后发布"],
     "将以下英文 changelog 改写为中文公众号推文：标题+三点更新+升级建议，不夸大。",
     "待审核的中文版本更新推文。",
     "Release 太技术时加「用类比解释」指令。"),
    ("2026-05-31", "openclaw-rss-summarize", "自动化", "OpenClaw", "🦞", "https://openclaw.ai", "入门", "约 18 分钟",
     "OpenClaw 聚合 RSS 并写入飞书多维表格",
     "定时抓 AI 博客 RSS，摘要后写入 Bitable 供团队浏览。",
     ["OpenClaw 新建 cron", "配置 RSS 列表", "Filter 已存在 GUID", "AI 生成 80 字摘要", "Feishu Bitable 新增行", "周报视图按日期分组"],
     "为每条 RSS 输出：中文标题、80字摘要、关键词3个、阅读原文链接。",
     "飞书表格里的 AI 资讯库。",
     "Bitable 字段先建好，避免写入失败。"),
    ("2026-05-30", "pipedream-youtube", "自动化", "Pipedream", "🚀", "https://pipedream.com", "进阶", "约 20 分钟",
     "Pipedream：YouTube 新视频→摘要邮件",
     "订阅频道更新，自动转录摘要并邮件推送。",
     ["Pipedream 选 YouTube New Video", "拉取字幕或音频转写", "OpenAI 三点摘要", "Send Email via SMTP", "去重已处理 videoId", "每日 9 点定时"],
     "根据字幕生成：①一句话主题 ②三条要点 ③是否值得看（1-5）中文。",
     "每日视频精选邮件。",
     "无字幕视频需先接 Whisper 步骤。"),
    ("2026-05-29", "ifttt-ios-shortcut", "自动化", "IFTTT", "📱", "https://ifttt.com", "入门", "约 12 分钟",
     "IFTTT + iOS 快捷指令：语音灵感→Notion AI 整理",
     "对 Siri 说灵感，自动进 Notion 并由 AI 补标签。",
     ["IFTTT 连接 iOS Shortcuts", "Shortcut 录音转文字", "Webhook 到 Notion API", "Notion AI 补全标签与关联", "通知确认写入", "测试语音流程"],
     "将语音转写整理为 Notion 笔记：标题+三条 bullet+标签#灵感#AI学习",
     "语音灵感到结构化笔记。",
     "嘈杂环境先手机编辑再发送。"),
    ("2026-05-28", "activepieces-crm", "自动化", "Activepieces", "🧱", "https://www.activepieces.com", "进阶", "约 24 分钟",
     "Activepieces 自托管：线索表单→CRM+AI 打分",
     "自托管 Activepieces，网站表单进 CRM 并 AI 评估线索质量。",
     ["Docker 部署 Activepieces", "Webhook 接收表单", "HTTP 写 HubSpot 联系人", "AI 打 Lead Score 1-5", "高分分支 Slack @sales", "低分进入培育序列"],
     "根据表单回答打线索分 1-5，输出 reason≤50字，JSON: {score, reason}",
     "带评分的 CRM 线索流水线。",
     "自托管注意备份加密凭据。"),

    # 办公效率 x8
    ("2026-05-27", "notion-ai-meeting", "办公效率", "Notion", "📝", "https://www.notion.so", "入门", "约 12 分钟",
     "Notion AI 会议笔记：议程→纪要→行动项",
     "会前写议程，会中贴要点，Notion AI 生成纪要与任务。",
     ["创建会议页模板含议程区", "会中 bullet 记录要点", "选中全文 Notion AI Summarize", "再 AI Extract action items", "转成数据库任务指派", "设截止日期提醒"],
     "根据议程与要点生成纪要：决策/讨论/行动项(负责人+DDL)，中文，不编造未讨论内容。",
     "结构化会议纪要+任务库。",
     "行动项一定指派到人，避免悬空。"),
    ("2026-05-26", "google-docs-draft", "办公效率", "Gemini", "✨", "https://workspace.google.com", "入门", "约 10 分钟",
     "Google Docs 内置 Gemini 起草方案大纲",
     "在 Docs 侧边栏用 Gemini 根据三点 bullet 扩成方案大纲。",
     ["新建 Google Doc", "写三条核心 bullet", "Gemini 侧边栏选 Help me write", "生成大纲后 Accept", "手动补数据与引用", "Share 评论收集反馈"],
     "将以下三点扩展为方案大纲：背景、目标、三阶段计划；每节 2-3 bullet；正式中文。",
     "可评审的方案初稿大纲。",
     "生成后务必人工补真实数据。"),
    ("2026-05-25", "excel-copilot-formula", "办公效率", "Copilot", "📊", "https://www.microsoft.com/microsoft-copilot", "入门", "约 12 分钟",
     "Excel Copilot 用自然语言写 XLOOKUP 公式",
     "描述跨表匹配需求，让 Copilot 生成并解释公式。",
     ["打开含两表工作簿", "Copilot 面板描述匹配逻辑", "插入公式到目标列", "检查 #N/A 行", "让 Copilot 改 IFERROR", "保存模板"],
     "根据订单表 SKU 从价目表取单价，写到订单表新列，找不到填「缺失」；用 XLOOKUP。",
     "正确的跨表匹配公式。",
     "先让 Copilot 「解释公式每一步」再复制。"),
    ("2026-05-24", "slack-summary", "办公效率", "Slack", "💼", "https://slack.com", "入门", "约 8 分钟",
     "Slack AI 线程摘要：长讨论 30 秒读完",
     "对 50+ 回复线程一键摘要决策与待办。",
     ["打开冗长项目线程", "点击 Summarize thread", "阅读 AI 摘要", "核对是否遗漏否决意见", "Pin 摘要到频道", "跟进未指派任务"],
     "（按钮操作为主）摘要后手动补充：负责人/截止日期/未决问题",
     "团队共识的快速回顾。",
     "摘要后仍要 @ 责任人确认。"),
    ("2026-05-23", "obsidian-copilot", "办公效率", "Obsidian", "🧠", "https://obsidian.md", "进阶", "约 20 分钟",
     "Obsidian Copilot 插件：库内问答学习笔记",
     "配置本地/云端模型，对整库笔记做引用式问答。",
     ["安装 Obsidian Copilot 插件", "设置 API 或 Ollama", "索引 vault 向量库", "提问「解释 RAG 我做的实验」", "检查引用链接跳转到笔记", "固定常用问题为命令"],
     "仅根据笔记回答；引用 [[笔记名]]；不知道就说未记录；中文简洁。",
     "带笔记引用的个人知识问答。",
     "定期 Reindex 避免新笔记搜不到。"),
    ("2026-05-22", "feishu-ai-doc", "办公效率", "飞书", "🐦", "https://www.feishu.cn", "入门", "约 15 分钟",
     "飞书文档 AI 将调研链接汇编成竞品表",
     "粘贴 5 个竞品链接要点，AI 生成对比表。",
     ["新建飞书文档", "粘贴竞品要点 bullet", "选 AI 创作→表格", "校对价格与功能", "加「未知」列避免瞎填", "分享团队只读"],
     "根据以下要点生成竞品对比表：功能/价格/中文支持/部署方式；缺失填「待核实」。",
     "可分享的竞品对比表。",
     "价格列标注「截至日期」。"),
    ("2026-05-21", "linear-ai-issue", "办公效率", "Linear", "📐", "https://linear.app", "进阶", "约 14 分钟",
     "Linear AI 把用户反馈拆成可执行 Issue",
     "粘贴 10 条用户反馈，AI 聚类并生成带优先级的 Issue。",
     ["Linear 项目新建 View", "粘贴反馈到 AI 助手", "要求按主题聚类", "生成 Issue 标题+验收标准", "人工调整优先级", "排入本周 Cycle"],
     "将反馈聚类为 Issue：标题、问题陈述、验收标准、优先级P0-2；不重复；中文。",
     "结构化的产品 Backlog。",
     "验收标准必须可测试。"),
    ("2026-05-20", "teams-recap", "办公效率", "Copilot", "📊", "https://www.microsoft.com/microsoft-teams", "入门", "约 10 分钟",
     "Teams 会议 Copilot 复盘：谁说了什么决策",
     "会后打开 Copilot 面板查看说话人分段与决策列表。",
     ["打开刚结束的 Teams 会议", "Copilot → Recap", "查看 Speakers & topics", "复制决策与行动项", "贴到 OneNote 项目页", "标注责任人"],
     "从会议转写提取：决策列表、未决问题、行动项(人+DDL)；不编造。",
     "可归档的会议决策记录。",
     "敏感会议先确认公司是否允许云转写。"),
]


def main():
    briefing = [mk_briefing(*t) for t in BRIEFING_TOPICS]
    tutorials = [mk_tutorial(*t) for t in TUTORIAL_TOPICS]

    assert len(briefing) == 40, len(briefing)
    assert len(tutorials) == 40, len(tutorials)

    for items, name in [(briefing, "ai-briefing-batch.json"), (tutorials, "latest-tutorials-batch.json")]:
        path = OUT_DIR / name
        path.write_text(json.dumps(items, ensure_ascii=False, indent=2), encoding="utf-8")
        cats = {}
        for it in items:
            c = it["category"]
            cats[c] = cats.get(c, 0) + 1
        print(f"{name}: {len(items)} items, categories={cats}")


if __name__ == "__main__":
    main()